// Code generated by 'ccgo limits/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o limits/limits_linux_amd64.go -pkgname limits -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package limits

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	ARG_MAX                              = 131072               // limits.h:49:1:
	BC_BASE_MAX                          = 99                   // limits.h:77:1:
	BC_DIM_MAX                           = 2048                 // limits.h:78:1:
	BC_SCALE_MAX                         = 99                   // limits.h:79:1:
	BC_STRING_MAX                        = 1000                 // limits.h:80:1:
	CHARCLASS_NAME_MAX                   = 14                   // limits.h:81:1:
	CHAR_BIT                             = 8                    // limits.h:18:1:
	CHAR_MAX                             = 255                  // limits.h:12:1:
	CHAR_MIN                             = 0                    // limits.h:11:1:
	COLL_WEIGHTS_MAX                     = 2                    // limits.h:82:1:
	DELAYTIMER_MAX                       = 0x7fffffff           // limits.h:71:1:
	EXPR_NEST_MAX                        = 32                   // limits.h:83:1:
	FEATURES_H                           = 0                    // features.h:2:1:
	FILESIZEBITS                         = 64                   // limits.h:43:1:
	HOST_NAME_MAX                        = 255                  // limits.h:56:1:
	INT_MAX                              = 0x7fffffff           // limits.h:26:1:
	INT_MIN                              = -2147483648          // limits.h:25:1:
	IOV_MAX                              = 1024                 // limits.h:50:1:
	LINE_MAX                             = 4096                 // limits.h:84:1:
	LLONG_MAX                            = 0x7fffffffffffffff   // limits.h:32:1:
	LLONG_MIN                            = -9223372036854775808 // limits.h:31:1:
	LOGIN_NAME_MAX                       = 256                  // limits.h:73:1:
	LONG_BIT                             = 64                   // limits.h:61:1:
	LONG_MAX                             = 9223372036854775807  // limits.h:29:1:
	LONG_MIN                             = -9223372036854775808 // limits.h:28:1:
	MB_LEN_MAX                           = 4                    // limits.h:35:1:
	MQ_PRIO_MAX                          = 32768                // limits.h:72:1:
	NAME_MAX                             = 255                  // limits.h:45:1:
	NGROUPS_MAX                          = 32                   // limits.h:48:1:
	NL_ARGMAX                            = 9                    // limits.h:87:1:
	NL_LANGMAX                           = 32                   // limits.h:100:1:
	NL_MSGMAX                            = 32767                // limits.h:88:1:
	NL_NMAX                              = 16                   // limits.h:107:1:
	NL_SETMAX                            = 255                  // limits.h:89:1:
	NL_TEXTMAX                           = 2048                 // limits.h:90:1:
	NZERO                                = 20                   // limits.h:99:1:
	PAGESIZE                             = 4096                 // limits.h:1:1:
	PAGE_SIZE                            = 4096                 // limits.h:97:1:
	PATH_MAX                             = 4096                 // limits.h:47:1:
	PIPE_BUF                             = 4096                 // limits.h:42:1:
	PTHREAD_DESTRUCTOR_ITERATIONS        = 4                    // limits.h:68:1:
	PTHREAD_KEYS_MAX                     = 128                  // limits.h:66:1:
	PTHREAD_STACK_MIN                    = 2048                 // limits.h:67:1:
	RE_DUP_MAX                           = 255                  // limits.h:85:1:
	SCHAR_MAX                            = 127                  // limits.h:20:1:
	SCHAR_MIN                            = -128                 // limits.h:19:1:
	SEM_NSEMS_MAX                        = 256                  // limits.h:70:1:
	SEM_VALUE_MAX                        = 0x7fffffff           // limits.h:69:1:
	SHRT_MAX                             = 0x7fff               // limits.h:23:1:
	SHRT_MIN                             = -32768               // limits.h:22:1:
	SSIZE_MAX                            = 9223372036854775807  // limits.h:53:1:
	SYMLOOP_MAX                          = 40                   // limits.h:51:1:
	TTY_NAME_MAX                         = 32                   // limits.h:55:1:
	TZNAME_MAX                           = 6                    // limits.h:54:1:
	UCHAR_MAX                            = 255                  // limits.h:21:1:
	UINT_MAX                             = 0xffffffff           // limits.h:27:1:
	ULLONG_MAX                           = 18446744073709551615 // limits.h:33:1:
	ULONG_MAX                            = 18446744073709551615 // limits.h:30:1:
	USHRT_MAX                            = 0xffff               // limits.h:24:1:
	WORD_BIT                             = 32                   // limits.h:52:1:
	X_BSD_SOURCE                         = 1                    // features.h:15:1:
	X_FEATURES_H                         = 0                    // features.h:2:1:
	X_FILE_OFFSET_BITS                   = 64                   // <builtin>:25:1:
	X_LIMITS_H                           = 0                    // limits.h:2:1:
	X_LP64                               = 1                    // <predefined>:312:1:
	X_POSIX2_BC_BASE_MAX                 = 99                   // limits.h:152:1:
	X_POSIX2_BC_DIM_MAX                  = 2048                 // limits.h:153:1:
	X_POSIX2_BC_SCALE_MAX                = 99                   // limits.h:154:1:
	X_POSIX2_BC_STRING_MAX               = 1000                 // limits.h:155:1:
	X_POSIX2_CHARCLASS_NAME_MAX          = 14                   // limits.h:156:1:
	X_POSIX2_COLL_WEIGHTS_MAX            = 2                    // limits.h:157:1:
	X_POSIX2_EXPR_NEST_MAX               = 32                   // limits.h:158:1:
	X_POSIX2_LINE_MAX                    = 2048                 // limits.h:159:1:
	X_POSIX2_RE_DUP_MAX                  = 255                  // limits.h:160:1:
	X_POSIX_AIO_LISTIO_MAX               = 2                    // limits.h:114:1:
	X_POSIX_AIO_MAX                      = 1                    // limits.h:115:1:
	X_POSIX_ARG_MAX                      = 4096                 // limits.h:116:1:
	X_POSIX_CHILD_MAX                    = 25                   // limits.h:117:1:
	X_POSIX_CLOCKRES_MIN                 = 20000000             // limits.h:118:1:
	X_POSIX_DELAYTIMER_MAX               = 32                   // limits.h:119:1:
	X_POSIX_HOST_NAME_MAX                = 255                  // limits.h:120:1:
	X_POSIX_LINK_MAX                     = 8                    // limits.h:121:1:
	X_POSIX_LOGIN_NAME_MAX               = 9                    // limits.h:122:1:
	X_POSIX_MAX_CANON                    = 255                  // limits.h:123:1:
	X_POSIX_MAX_INPUT                    = 255                  // limits.h:124:1:
	X_POSIX_MQ_OPEN_MAX                  = 8                    // limits.h:125:1:
	X_POSIX_MQ_PRIO_MAX                  = 32                   // limits.h:126:1:
	X_POSIX_NAME_MAX                     = 14                   // limits.h:127:1:
	X_POSIX_NGROUPS_MAX                  = 8                    // limits.h:128:1:
	X_POSIX_OPEN_MAX                     = 20                   // limits.h:129:1:
	X_POSIX_PATH_MAX                     = 256                  // limits.h:130:1:
	X_POSIX_PIPE_BUF                     = 512                  // limits.h:131:1:
	X_POSIX_RE_DUP_MAX                   = 255                  // limits.h:132:1:
	X_POSIX_RTSIG_MAX                    = 8                    // limits.h:133:1:
	X_POSIX_SEM_NSEMS_MAX                = 256                  // limits.h:134:1:
	X_POSIX_SEM_VALUE_MAX                = 32767                // limits.h:135:1:
	X_POSIX_SIGQUEUE_MAX                 = 32                   // limits.h:136:1:
	X_POSIX_SSIZE_MAX                    = 32767                // limits.h:137:1:
	X_POSIX_SS_REPL_MAX                  = 4                    // limits.h:139:1:
	X_POSIX_STREAM_MAX                   = 8                    // limits.h:138:1:
	X_POSIX_SYMLINK_MAX                  = 255                  // limits.h:140:1:
	X_POSIX_SYMLOOP_MAX                  = 8                    // limits.h:141:1:
	X_POSIX_THREAD_DESTRUCTOR_ITERATIONS = 4                    // limits.h:142:1:
	X_POSIX_THREAD_KEYS_MAX              = 128                  // limits.h:143:1:
	X_POSIX_THREAD_THREADS_MAX           = 64                   // limits.h:144:1:
	X_POSIX_TIMER_MAX                    = 32                   // limits.h:145:1:
	X_POSIX_TRACE_EVENT_NAME_MAX         = 30                   // limits.h:146:1:
	X_POSIX_TRACE_NAME_MAX               = 8                    // limits.h:147:1:
	X_POSIX_TRACE_SYS_MAX                = 8                    // limits.h:148:1:
	X_POSIX_TRACE_USER_EVENT_MAX         = 32                   // limits.h:149:1:
	X_POSIX_TTY_NAME_MAX                 = 9                    // limits.h:150:1:
	X_POSIX_TZNAME_MAX                   = 6                    // limits.h:151:1:
	X_STDC_PREDEF_H                      = 1                    // <predefined>:174:1:
	X_XOPEN_IOV_MAX                      = 16                   // limits.h:162:1:
	X_XOPEN_NAME_MAX                     = 255                  // limits.h:163:1:
	X_XOPEN_PATH_MAX                     = 1024                 // limits.h:164:1:
	X_XOPEN_SOURCE                       = 700                  // features.h:16:1:
	Linux                                = 1                    // <predefined>:255:1:
	Unix                                 = 1                    // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

// Support signed or unsigned plain-char

// Implementation choices...

// Arbitrary numbers...

// POSIX/SUS requirements follow. These numbers come directly
// from SUS and have nothing to do with the host system.

var _ int8 /* gen.c:2:13: */
