// Code generated by 'ccgo stdio/gen.c -crt-import-path  -export-defines  -export-enums  -export-externs X -nostdinc -nostdlib -export-fields F -export-structs  -export-typedefs  -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o stdio/stdio_linux_amd64.go -pkgname stdio -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package stdio

var CAPI = map[string]struct{}{
	"__syscall0": {},
	"__syscall1": {},
	"__syscall2": {},
	"__syscall3": {},
	"__syscall4": {},
	"__syscall5": {},
	"__syscall6": {},
}
