// Code generated by 'ccgo stdio/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o stdio/stdio_linux_amd64.go -pkgname stdio -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package stdio

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	BUFSIZ                     = 1024                   // stdio.h:48:1:
	EOF                        = -1                     // stdio.h:35:1:
	FEATURES_H                 = 0                      // features.h:2:1:
	FILENAME_MAX               = 4096                   // stdio.h:49:1:
	FOPEN_MAX                  = 1000                   // stdio.h:50:1:
	F_APP                      = 128                    // stdio_impl.h:19:1:
	F_EOF                      = 16                     // stdio_impl.h:16:1:
	F_ERR                      = 32                     // stdio_impl.h:17:1:
	F_NORD                     = 4                      // stdio_impl.h:14:1:
	F_NOWR                     = 8                      // stdio_impl.h:15:1:
	F_PERM                     = 1                      // stdio_impl.h:13:1:
	F_SVB                      = 64                     // stdio_impl.h:18:1:
	IPC_64                     = 0                      // syscall_arch.h:70:1:
	L_ctermid                  = 20                     // stdio.h:156:1:
	L_cuserid                  = 20                     // stdio.h:167:1:
	L_tmpnam                   = 20                     // stdio.h:52:1:
	MAYBE_WAITERS              = 0x40000000             // stdio_impl.h:93:1:
	P_tmpdir                   = "/tmp"                 // stdio.h:162:1:
	SCM_TIMESTAMPING_OLD       = 37                     // syscall.h:353:1:
	SCM_TIMESTAMPNS_OLD        = 35                     // syscall.h:352:1:
	SCM_TIMESTAMP_OLD          = 29                     // syscall.h:351:1:
	SEEK_CUR                   = 1                      // stdio.h:41:1:
	SEEK_END                   = 2                      // stdio.h:42:1:
	SEEK_SET                   = 0                      // stdio.h:40:1:
	SIOCGSTAMPNS_OLD           = 0x8907                 // syscall.h:359:1:
	SIOCGSTAMP_OLD             = 0x8906                 // syscall.h:356:1:
	SO_RCVTIMEO_OLD            = 20                     // syscall.h:342:1:
	SO_SNDTIMEO_OLD            = 21                     // syscall.h:345:1:
	SO_TIMESTAMPING_OLD        = 37                     // syscall.h:350:1:
	SO_TIMESTAMPNS_OLD         = 35                     // syscall.h:349:1:
	SO_TIMESTAMP_OLD           = 29                     // syscall.h:348:1:
	STDIO_H                    = 0                      // stdio.h:2:1:
	SYSCALL_MMAP2_UNIT         = 4096                   // syscall.h:13:1:
	SYSCALL_RLIM_INFINITY      = 18446744073709551615   // syscall.h:9:1:
	SYS__sysctl                = 156                    // syscall.h:505:1:
	SYS_accept                 = 43                     // syscall.h:392:1:
	SYS_accept4                = 288                    // syscall.h:637:1:
	SYS_access                 = 21                     // syscall.h:370:1:
	SYS_acct                   = 163                    // syscall.h:512:1:
	SYS_add_key                = 248                    // syscall.h:597:1:
	SYS_adjtimex               = 159                    // syscall.h:508:1:
	SYS_afs_syscall            = 183                    // syscall.h:532:1:
	SYS_alarm                  = 37                     // syscall.h:386:1:
	SYS_arch_prctl             = 158                    // syscall.h:507:1:
	SYS_bind                   = 49                     // syscall.h:398:1:
	SYS_bpf                    = 321                    // syscall.h:670:1:
	SYS_brk                    = 12                     // syscall.h:361:1:
	SYS_capget                 = 125                    // syscall.h:474:1:
	SYS_capset                 = 126                    // syscall.h:475:1:
	SYS_chdir                  = 80                     // syscall.h:429:1:
	SYS_chmod                  = 90                     // syscall.h:439:1:
	SYS_chown                  = 92                     // syscall.h:441:1:
	SYS_chroot                 = 161                    // syscall.h:510:1:
	SYS_clock_adjtime          = 305                    // syscall.h:654:1:
	SYS_clock_getres           = 229                    // syscall.h:578:1:
	SYS_clock_gettime          = 228                    // syscall.h:577:1:
	SYS_clock_nanosleep        = 230                    // syscall.h:579:1:
	SYS_clock_settime          = 227                    // syscall.h:576:1:
	SYS_clone                  = 56                     // syscall.h:405:1:
	SYS_clone3                 = 435                    // syscall.h:695:1:
	SYS_close                  = 3                      // syscall.h:352:1:
	SYS_connect                = 42                     // syscall.h:391:1:
	SYS_copy_file_range        = 326                    // syscall.h:675:1:
	SYS_creat                  = 85                     // syscall.h:434:1:
	SYS_create_module          = 174                    // syscall.h:523:1:
	SYS_delete_module          = 176                    // syscall.h:525:1:
	SYS_dup                    = 32                     // syscall.h:381:1:
	SYS_dup2                   = 33                     // syscall.h:382:1:
	SYS_dup3                   = 292                    // syscall.h:641:1:
	SYS_epoll_create           = 213                    // syscall.h:562:1:
	SYS_epoll_create1          = 291                    // syscall.h:640:1:
	SYS_epoll_ctl              = 233                    // syscall.h:582:1:
	SYS_epoll_ctl_old          = 214                    // syscall.h:563:1:
	SYS_epoll_pwait            = 281                    // syscall.h:630:1:
	SYS_epoll_wait             = 232                    // syscall.h:581:1:
	SYS_epoll_wait_old         = 215                    // syscall.h:564:1:
	SYS_eventfd                = 284                    // syscall.h:633:1:
	SYS_eventfd2               = 290                    // syscall.h:639:1:
	SYS_execve                 = 59                     // syscall.h:408:1:
	SYS_execveat               = 322                    // syscall.h:671:1:
	SYS_exit                   = 60                     // syscall.h:409:1:
	SYS_exit_group             = 231                    // syscall.h:580:1:
	SYS_faccessat              = 269                    // syscall.h:618:1:
	SYS_fadvise                = 221                    // syscall.h:188:1:
	SYS_fadvise64              = 221                    // syscall.h:570:1:
	SYS_fallocate              = 285                    // syscall.h:634:1:
	SYS_fanotify_init          = 300                    // syscall.h:649:1:
	SYS_fanotify_mark          = 301                    // syscall.h:650:1:
	SYS_fchdir                 = 81                     // syscall.h:430:1:
	SYS_fchmod                 = 91                     // syscall.h:440:1:
	SYS_fchmodat               = 268                    // syscall.h:617:1:
	SYS_fchown                 = 93                     // syscall.h:442:1:
	SYS_fchownat               = 260                    // syscall.h:609:1:
	SYS_fcntl                  = 72                     // syscall.h:421:1:
	SYS_fdatasync              = 75                     // syscall.h:424:1:
	SYS_fgetxattr              = 193                    // syscall.h:542:1:
	SYS_finit_module           = 313                    // syscall.h:662:1:
	SYS_flistxattr             = 196                    // syscall.h:545:1:
	SYS_flock                  = 73                     // syscall.h:422:1:
	SYS_fork                   = 57                     // syscall.h:406:1:
	SYS_fremovexattr           = 199                    // syscall.h:548:1:
	SYS_fsconfig               = 431                    // syscall.h:691:1:
	SYS_fsetxattr              = 190                    // syscall.h:539:1:
	SYS_fsmount                = 432                    // syscall.h:692:1:
	SYS_fsopen                 = 430                    // syscall.h:690:1:
	SYS_fspick                 = 433                    // syscall.h:693:1:
	SYS_fstat                  = 5                      // syscall.h:354:1:
	SYS_fstatat                = 262                    // syscall.h:160:1:
	SYS_fstatfs                = 138                    // syscall.h:487:1:
	SYS_fsync                  = 74                     // syscall.h:423:1:
	SYS_ftruncate              = 77                     // syscall.h:426:1:
	SYS_futex                  = 202                    // syscall.h:551:1:
	SYS_futimesat              = 261                    // syscall.h:610:1:
	SYS_get_kernel_syms        = 177                    // syscall.h:526:1:
	SYS_get_mempolicy          = 239                    // syscall.h:588:1:
	SYS_get_robust_list        = 274                    // syscall.h:623:1:
	SYS_get_thread_area        = 211                    // syscall.h:560:1:
	SYS_getcpu                 = 309                    // syscall.h:658:1:
	SYS_getcwd                 = 79                     // syscall.h:428:1:
	SYS_getdents               = 217                    // syscall.h:123:1:
	SYS_getdents64             = 217                    // syscall.h:566:1:
	SYS_getegid                = 108                    // syscall.h:457:1:
	SYS_geteuid                = 107                    // syscall.h:456:1:
	SYS_getgid                 = 104                    // syscall.h:453:1:
	SYS_getgroups              = 115                    // syscall.h:464:1:
	SYS_getitimer              = 36                     // syscall.h:385:1:
	SYS_getpeername            = 52                     // syscall.h:401:1:
	SYS_getpgid                = 121                    // syscall.h:470:1:
	SYS_getpgrp                = 111                    // syscall.h:460:1:
	SYS_getpid                 = 39                     // syscall.h:388:1:
	SYS_getpmsg                = 181                    // syscall.h:530:1:
	SYS_getppid                = 110                    // syscall.h:459:1:
	SYS_getpriority            = 140                    // syscall.h:489:1:
	SYS_getrandom              = 318                    // syscall.h:667:1:
	SYS_getresgid              = 120                    // syscall.h:469:1:
	SYS_getresuid              = 118                    // syscall.h:467:1:
	SYS_getrlimit              = 97                     // syscall.h:446:1:
	SYS_getrusage              = 98                     // syscall.h:447:1:
	SYS_getsid                 = 124                    // syscall.h:473:1:
	SYS_getsockname            = 51                     // syscall.h:400:1:
	SYS_getsockopt             = 55                     // syscall.h:404:1:
	SYS_gettid                 = 186                    // syscall.h:535:1:
	SYS_gettimeofday           = 96                     // syscall.h:445:1:
	SYS_getuid                 = 102                    // syscall.h:451:1:
	SYS_getxattr               = 191                    // syscall.h:540:1:
	SYS_init_module            = 175                    // syscall.h:524:1:
	SYS_inotify_add_watch      = 254                    // syscall.h:603:1:
	SYS_inotify_init           = 253                    // syscall.h:602:1:
	SYS_inotify_init1          = 294                    // syscall.h:643:1:
	SYS_inotify_rm_watch       = 255                    // syscall.h:604:1:
	SYS_io_cancel              = 210                    // syscall.h:559:1:
	SYS_io_destroy             = 207                    // syscall.h:556:1:
	SYS_io_getevents           = 208                    // syscall.h:557:1:
	SYS_io_pgetevents          = 333                    // syscall.h:682:1:
	SYS_io_setup               = 206                    // syscall.h:555:1:
	SYS_io_submit              = 209                    // syscall.h:558:1:
	SYS_io_uring_enter         = 426                    // syscall.h:686:1:
	SYS_io_uring_register      = 427                    // syscall.h:687:1:
	SYS_io_uring_setup         = 425                    // syscall.h:685:1:
	SYS_ioctl                  = 16                     // syscall.h:365:1:
	SYS_ioperm                 = 173                    // syscall.h:522:1:
	SYS_iopl                   = 172                    // syscall.h:521:1:
	SYS_ioprio_get             = 252                    // syscall.h:601:1:
	SYS_ioprio_set             = 251                    // syscall.h:600:1:
	SYS_kcmp                   = 312                    // syscall.h:661:1:
	SYS_kexec_file_load        = 320                    // syscall.h:669:1:
	SYS_kexec_load             = 246                    // syscall.h:595:1:
	SYS_keyctl                 = 250                    // syscall.h:599:1:
	SYS_kill                   = 62                     // syscall.h:411:1:
	SYS_lchown                 = 94                     // syscall.h:443:1:
	SYS_lgetxattr              = 192                    // syscall.h:541:1:
	SYS_link                   = 86                     // syscall.h:435:1:
	SYS_linkat                 = 265                    // syscall.h:614:1:
	SYS_listen                 = 50                     // syscall.h:399:1:
	SYS_listxattr              = 194                    // syscall.h:543:1:
	SYS_llistxattr             = 195                    // syscall.h:544:1:
	SYS_lookup_dcookie         = 212                    // syscall.h:561:1:
	SYS_lremovexattr           = 198                    // syscall.h:547:1:
	SYS_lseek                  = 8                      // syscall.h:357:1:
	SYS_lsetxattr              = 189                    // syscall.h:538:1:
	SYS_lstat                  = 6                      // syscall.h:355:1:
	SYS_madvise                = 28                     // syscall.h:377:1:
	SYS_mbind                  = 237                    // syscall.h:586:1:
	SYS_membarrier             = 324                    // syscall.h:673:1:
	SYS_memfd_create           = 319                    // syscall.h:668:1:
	SYS_migrate_pages          = 256                    // syscall.h:605:1:
	SYS_mincore                = 27                     // syscall.h:376:1:
	SYS_mkdir                  = 83                     // syscall.h:432:1:
	SYS_mkdirat                = 258                    // syscall.h:607:1:
	SYS_mknod                  = 133                    // syscall.h:482:1:
	SYS_mknodat                = 259                    // syscall.h:608:1:
	SYS_mlock                  = 149                    // syscall.h:498:1:
	SYS_mlock2                 = 325                    // syscall.h:674:1:
	SYS_mlockall               = 151                    // syscall.h:500:1:
	SYS_mmap                   = 9                      // syscall.h:358:1:
	SYS_modify_ldt             = 154                    // syscall.h:503:1:
	SYS_mount                  = 165                    // syscall.h:514:1:
	SYS_move_mount             = 429                    // syscall.h:689:1:
	SYS_move_pages             = 279                    // syscall.h:628:1:
	SYS_mprotect               = 10                     // syscall.h:359:1:
	SYS_mq_getsetattr          = 245                    // syscall.h:594:1:
	SYS_mq_notify              = 244                    // syscall.h:593:1:
	SYS_mq_open                = 240                    // syscall.h:589:1:
	SYS_mq_timedreceive        = 243                    // syscall.h:592:1:
	SYS_mq_timedsend           = 242                    // syscall.h:591:1:
	SYS_mq_unlink              = 241                    // syscall.h:590:1:
	SYS_mremap                 = 25                     // syscall.h:374:1:
	SYS_msgctl                 = 71                     // syscall.h:420:1:
	SYS_msgget                 = 68                     // syscall.h:417:1:
	SYS_msgrcv                 = 70                     // syscall.h:419:1:
	SYS_msgsnd                 = 69                     // syscall.h:418:1:
	SYS_msync                  = 26                     // syscall.h:375:1:
	SYS_munlock                = 150                    // syscall.h:499:1:
	SYS_munlockall             = 152                    // syscall.h:501:1:
	SYS_munmap                 = 11                     // syscall.h:360:1:
	SYS_name_to_handle_at      = 303                    // syscall.h:652:1:
	SYS_nanosleep              = 35                     // syscall.h:384:1:
	SYS_newfstatat             = 262                    // syscall.h:611:1:
	SYS_nfsservctl             = 180                    // syscall.h:529:1:
	SYS_open                   = 2                      // syscall.h:351:1:
	SYS_open_by_handle_at      = 304                    // syscall.h:653:1:
	SYS_open_tree              = 428                    // syscall.h:688:1:
	SYS_openat                 = 257                    // syscall.h:606:1:
	SYS_pause                  = 34                     // syscall.h:383:1:
	SYS_perf_event_open        = 298                    // syscall.h:647:1:
	SYS_personality            = 135                    // syscall.h:484:1:
	SYS_pidfd_open             = 434                    // syscall.h:694:1:
	SYS_pidfd_send_signal      = 424                    // syscall.h:684:1:
	SYS_pipe                   = 22                     // syscall.h:371:1:
	SYS_pipe2                  = 293                    // syscall.h:642:1:
	SYS_pivot_root             = 155                    // syscall.h:504:1:
	SYS_pkey_alloc             = 330                    // syscall.h:679:1:
	SYS_pkey_free              = 331                    // syscall.h:680:1:
	SYS_pkey_mprotect          = 329                    // syscall.h:678:1:
	SYS_poll                   = 7                      // syscall.h:356:1:
	SYS_ppoll                  = 271                    // syscall.h:620:1:
	SYS_prctl                  = 157                    // syscall.h:506:1:
	SYS_pread                  = 17                     // syscall.h:179:1:
	SYS_pread64                = 17                     // syscall.h:366:1:
	SYS_preadv                 = 295                    // syscall.h:644:1:
	SYS_preadv2                = 327                    // syscall.h:676:1:
	SYS_prlimit64              = 302                    // syscall.h:651:1:
	SYS_process_vm_readv       = 310                    // syscall.h:659:1:
	SYS_process_vm_writev      = 311                    // syscall.h:660:1:
	SYS_pselect6               = 270                    // syscall.h:619:1:
	SYS_ptrace                 = 101                    // syscall.h:450:1:
	SYS_putpmsg                = 182                    // syscall.h:531:1:
	SYS_pwrite                 = 18                     // syscall.h:180:1:
	SYS_pwrite64               = 18                     // syscall.h:367:1:
	SYS_pwritev                = 296                    // syscall.h:645:1:
	SYS_pwritev2               = 328                    // syscall.h:677:1:
	SYS_query_module           = 178                    // syscall.h:527:1:
	SYS_quotactl               = 179                    // syscall.h:528:1:
	SYS_read                   = 0                      // syscall.h:349:1:
	SYS_readahead              = 187                    // syscall.h:536:1:
	SYS_readlink               = 89                     // syscall.h:438:1:
	SYS_readlinkat             = 267                    // syscall.h:616:1:
	SYS_readv                  = 19                     // syscall.h:368:1:
	SYS_reboot                 = 169                    // syscall.h:518:1:
	SYS_recvfrom               = 45                     // syscall.h:394:1:
	SYS_recvmmsg               = 299                    // syscall.h:648:1:
	SYS_recvmsg                = 47                     // syscall.h:396:1:
	SYS_remap_file_pages       = 216                    // syscall.h:565:1:
	SYS_removexattr            = 197                    // syscall.h:546:1:
	SYS_rename                 = 82                     // syscall.h:431:1:
	SYS_renameat               = 264                    // syscall.h:613:1:
	SYS_renameat2              = 316                    // syscall.h:665:1:
	SYS_request_key            = 249                    // syscall.h:598:1:
	SYS_restart_syscall        = 219                    // syscall.h:568:1:
	SYS_rmdir                  = 84                     // syscall.h:433:1:
	SYS_rseq                   = 334                    // syscall.h:683:1:
	SYS_rt_sigaction           = 13                     // syscall.h:362:1:
	SYS_rt_sigpending          = 127                    // syscall.h:476:1:
	SYS_rt_sigprocmask         = 14                     // syscall.h:363:1:
	SYS_rt_sigqueueinfo        = 129                    // syscall.h:478:1:
	SYS_rt_sigreturn           = 15                     // syscall.h:364:1:
	SYS_rt_sigsuspend          = 130                    // syscall.h:479:1:
	SYS_rt_sigtimedwait        = 128                    // syscall.h:477:1:
	SYS_rt_tgsigqueueinfo      = 297                    // syscall.h:646:1:
	SYS_sched_get_priority_max = 146                    // syscall.h:495:1:
	SYS_sched_get_priority_min = 147                    // syscall.h:496:1:
	SYS_sched_getaffinity      = 204                    // syscall.h:553:1:
	SYS_sched_getattr          = 315                    // syscall.h:664:1:
	SYS_sched_getparam         = 143                    // syscall.h:492:1:
	SYS_sched_getscheduler     = 145                    // syscall.h:494:1:
	SYS_sched_rr_get_interval  = 148                    // syscall.h:497:1:
	SYS_sched_setaffinity      = 203                    // syscall.h:552:1:
	SYS_sched_setattr          = 314                    // syscall.h:663:1:
	SYS_sched_setparam         = 142                    // syscall.h:491:1:
	SYS_sched_setscheduler     = 144                    // syscall.h:493:1:
	SYS_sched_yield            = 24                     // syscall.h:373:1:
	SYS_seccomp                = 317                    // syscall.h:666:1:
	SYS_security               = 185                    // syscall.h:534:1:
	SYS_select                 = 23                     // syscall.h:372:1:
	SYS_semctl                 = 66                     // syscall.h:415:1:
	SYS_semget                 = 64                     // syscall.h:413:1:
	SYS_semop                  = 65                     // syscall.h:414:1:
	SYS_semtimedop             = 220                    // syscall.h:569:1:
	SYS_sendfile               = 40                     // syscall.h:389:1:
	SYS_sendmmsg               = 307                    // syscall.h:656:1:
	SYS_sendmsg                = 46                     // syscall.h:395:1:
	SYS_sendto                 = 44                     // syscall.h:393:1:
	SYS_set_mempolicy          = 238                    // syscall.h:587:1:
	SYS_set_robust_list        = 273                    // syscall.h:622:1:
	SYS_set_thread_area        = 205                    // syscall.h:554:1:
	SYS_set_tid_address        = 218                    // syscall.h:567:1:
	SYS_setdomainname          = 171                    // syscall.h:520:1:
	SYS_setfsgid               = 123                    // syscall.h:472:1:
	SYS_setfsuid               = 122                    // syscall.h:471:1:
	SYS_setgid                 = 106                    // syscall.h:455:1:
	SYS_setgroups              = 116                    // syscall.h:465:1:
	SYS_sethostname            = 170                    // syscall.h:519:1:
	SYS_setitimer              = 38                     // syscall.h:387:1:
	SYS_setns                  = 308                    // syscall.h:657:1:
	SYS_setpgid                = 109                    // syscall.h:458:1:
	SYS_setpriority            = 141                    // syscall.h:490:1:
	SYS_setregid               = 114                    // syscall.h:463:1:
	SYS_setresgid              = 119                    // syscall.h:468:1:
	SYS_setresuid              = 117                    // syscall.h:466:1:
	SYS_setreuid               = 113                    // syscall.h:462:1:
	SYS_setrlimit              = 160                    // syscall.h:509:1:
	SYS_setsid                 = 112                    // syscall.h:461:1:
	SYS_setsockopt             = 54                     // syscall.h:403:1:
	SYS_settimeofday           = 164                    // syscall.h:513:1:
	SYS_setuid                 = 105                    // syscall.h:454:1:
	SYS_setxattr               = 188                    // syscall.h:537:1:
	SYS_shmat                  = 30                     // syscall.h:379:1:
	SYS_shmctl                 = 31                     // syscall.h:380:1:
	SYS_shmdt                  = 67                     // syscall.h:416:1:
	SYS_shmget                 = 29                     // syscall.h:378:1:
	SYS_shutdown               = 48                     // syscall.h:397:1:
	SYS_sigaltstack            = 131                    // syscall.h:480:1:
	SYS_signalfd               = 282                    // syscall.h:631:1:
	SYS_signalfd4              = 289                    // syscall.h:638:1:
	SYS_socket                 = 41                     // syscall.h:390:1:
	SYS_socketpair             = 53                     // syscall.h:402:1:
	SYS_splice                 = 275                    // syscall.h:624:1:
	SYS_stat                   = 4                      // syscall.h:353:1:
	SYS_statfs                 = 137                    // syscall.h:486:1:
	SYS_statx                  = 332                    // syscall.h:681:1:
	SYS_swapoff                = 168                    // syscall.h:517:1:
	SYS_swapon                 = 167                    // syscall.h:516:1:
	SYS_symlink                = 88                     // syscall.h:437:1:
	SYS_symlinkat              = 266                    // syscall.h:615:1:
	SYS_sync                   = 162                    // syscall.h:511:1:
	SYS_sync_file_range        = 277                    // syscall.h:626:1:
	SYS_syncfs                 = 306                    // syscall.h:655:1:
	SYS_sysfs                  = 139                    // syscall.h:488:1:
	SYS_sysinfo                = 99                     // syscall.h:448:1:
	SYS_syslog                 = 103                    // syscall.h:452:1:
	SYS_tee                    = 276                    // syscall.h:625:1:
	SYS_tgkill                 = 234                    // syscall.h:583:1:
	SYS_time                   = 201                    // syscall.h:550:1:
	SYS_timer_create           = 222                    // syscall.h:571:1:
	SYS_timer_delete           = 226                    // syscall.h:575:1:
	SYS_timer_getoverrun       = 225                    // syscall.h:574:1:
	SYS_timer_gettime          = 224                    // syscall.h:573:1:
	SYS_timer_settime          = 223                    // syscall.h:572:1:
	SYS_timerfd_create         = 283                    // syscall.h:632:1:
	SYS_timerfd_gettime        = 287                    // syscall.h:636:1:
	SYS_timerfd_settime        = 286                    // syscall.h:635:1:
	SYS_times                  = 100                    // syscall.h:449:1:
	SYS_tkill                  = 200                    // syscall.h:549:1:
	SYS_truncate               = 76                     // syscall.h:425:1:
	SYS_tuxcall                = 184                    // syscall.h:533:1:
	SYS_umask                  = 95                     // syscall.h:444:1:
	SYS_umount2                = 166                    // syscall.h:515:1:
	SYS_uname                  = 63                     // syscall.h:412:1:
	SYS_unlink                 = 87                     // syscall.h:436:1:
	SYS_unlinkat               = 263                    // syscall.h:612:1:
	SYS_unshare                = 272                    // syscall.h:621:1:
	SYS_uselib                 = 134                    // syscall.h:483:1:
	SYS_userfaultfd            = 323                    // syscall.h:672:1:
	SYS_ustat                  = 136                    // syscall.h:485:1:
	SYS_utime                  = 132                    // syscall.h:481:1:
	SYS_utimensat              = 280                    // syscall.h:629:1:
	SYS_utimes                 = 235                    // syscall.h:584:1:
	SYS_vfork                  = 58                     // syscall.h:407:1:
	SYS_vhangup                = 153                    // syscall.h:502:1:
	SYS_vmsplice               = 278                    // syscall.h:627:1:
	SYS_vserver                = 236                    // syscall.h:585:1:
	SYS_wait4                  = 61                     // syscall.h:410:1:
	SYS_waitid                 = 247                    // syscall.h:596:1:
	SYS_write                  = 1                      // syscall.h:350:1:
	SYS_writev                 = 20                     // syscall.h:369:1:
	TMP_MAX                    = 10000                  // stdio.h:51:1:
	UNGET                      = 8                      // stdio_impl.h:7:1:
	VDSO_CGT_SYM               = "__vdso_clock_gettime" // syscall_arch.h:65:1:
	VDSO_CGT_VER               = "LINUX_2.6"            // syscall_arch.h:66:1:
	VDSO_GETCPU_SYM            = "__vdso_getcpu"        // syscall_arch.h:67:1:
	VDSO_GETCPU_VER            = "LINUX_2.6"            // syscall_arch.h:68:1:
	VDSO_USEFUL                = 0                      // syscall_arch.h:64:1:
	X_BSD_SOURCE               = 1                      // features.h:15:1:
	X_FEATURES_H               = 0                      // features.h:2:1:
	X_FILE_OFFSET_BITS         = 64                     // <builtin>:25:1:
	X_INTERNAL_SYSCALL_H       = 0                      // syscall.h:2:1:
	X_IOFBF                    = 0                      // stdio.h:44:1:
	X_IOLBF                    = 1                      // stdio.h:45:1:
	X_IONBF                    = 2                      // stdio.h:46:1:
	X_LP64                     = 1                      // <predefined>:312:1:
	X_STDC_PREDEF_H            = 1                      // <predefined>:174:1:
	X_STDIO_H                  = 0                      // stdio.h:2:1:
	X_STDIO_IMPL_H             = 0                      // stdio_impl.h:2:1:
	X_SYS_SYSCALL_H            = 0                      // syscall.h:2:1:
	X_XOPEN_SOURCE             = 700                    // features.h:16:1:
	Linux                      = 1                      // <predefined>:255:1:
	Unix                       = 1                      // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Ssize_t = int64 /* alltypes.h:65:15 */

type Off_t = int64 /* alltypes.h:162:16 */

type X_IO_FILE = struct {
	Fflags        uint32
	F__ccgo_pad1  [4]byte
	Frpos         uintptr
	Frend         uintptr
	Fclose        uintptr
	Fwend         uintptr
	Fwpos         uintptr
	Fmustbezero_1 uintptr
	Fwbase        uintptr
	Fread         uintptr
	Fwrite        uintptr
	Fseek         uintptr
	Fbuf          uintptr
	Fbuf_size     Size_t
	Fprev         uintptr
	Fnext         uintptr
	Ffd           int32
	Fpipe_pid     int32
	Flockcount    int64
	Fmode         int32
	Flock         int32
	Flbf          int32
	F__ccgo_pad2  [4]byte
	Fcookie       uintptr
	Foff          Off_t
	Fgetln_buf    uintptr
	Fmustbezero_2 uintptr
	Fshend        uintptr
	Fshlim        Off_t
	Fshcnt        Off_t
	Fprev_locked  uintptr
	Fnext_locked  uintptr
	Flocale       uintptr
} /* alltypes.h:320:9 */

type FILE = X_IO_FILE /* alltypes.h:320:25 */

type Va_list = X__builtin_va_list /* alltypes.h:326:27 */

type X__isoc_va_list = X__builtin_va_list /* alltypes.h:331:27 */

type X_G_fpos64_t = struct {
	F__ccgo_pad1 [0]uint64
	F__opaque    [16]int8
} /* stdio.h:54:9 */

type Fpos_t = X_G_fpos64_t /* stdio.h:58:3 */

type Syscall_arg_t = int64 /* syscall.h:22:14 */

var _ int8 /* gen.c:4:16: */
