// Code generated by 'ccgo sys/types/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o sys/types/types_linux_amd64.go -pkgname types -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package types

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	BIG_ENDIAN         = 4321 // endian.h:14:1:
	BYTE_ORDER         = 1234 // endian.h:17:1:
	FD_SETSIZE         = 1024 // select.h:18:1:
	FEATURES_H         = 0    // features.h:2:1:
	LITTLE_ENDIAN      = 1234 // endian.h:15:1:
	PDP_ENDIAN         = 3412 // endian.h:16:1:
	X_BSD_SOURCE       = 1    // features.h:15:1:
	X_ENDIAN_H         = 0    // endian.h:2:1:
	X_FEATURES_H       = 0    // features.h:2:1:
	X_FILE_OFFSET_BITS = 64   // <builtin>:25:1:
	X_LP64             = 1    // <predefined>:312:1:
	X_STDC_PREDEF_H    = 1    // <predefined>:174:1:
	X_SYS_SELECT_H     = 0    // select.h:2:1:
	X_SYS_TYPES_H      = 0    // types.h:2:1:
	X_XOPEN_SOURCE     = 700  // features.h:16:1:
	Linux              = 1    // <predefined>:255:1:
	Unix               = 1    // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Ssize_t = int64 /* alltypes.h:65:15 */

type Register_t = int64 /* alltypes.h:80:14 */

type Time_t = int64 /* alltypes.h:85:16 */

type Suseconds_t = int64 /* alltypes.h:90:16 */

type Int8_t = int8 /* alltypes.h:96:25 */

type Int16_t = int16 /* alltypes.h:101:25 */

type Int32_t = int32 /* alltypes.h:106:25 */

type Int64_t = int64 /* alltypes.h:111:25 */

type U_int64_t = uint64 /* alltypes.h:141:25 */

type Mode_t = uint32 /* alltypes.h:152:18 */

type Nlink_t = uint64 /* alltypes.h:157:23 */

type Off_t = int64 /* alltypes.h:162:16 */

type Ino_t = uint64 /* alltypes.h:167:25 */

type Dev_t = uint64 /* alltypes.h:172:25 */

type Blksize_t = int64 /* alltypes.h:177:14 */

type Blkcnt_t = int64 /* alltypes.h:182:16 */

type Fsblkcnt_t = uint64 /* alltypes.h:187:25 */

type Fsfilcnt_t = uint64 /* alltypes.h:192:25 */

type Timer_t = uintptr /* alltypes.h:209:14 */

type Clockid_t = int32 /* alltypes.h:214:13 */

type Clock_t = int64 /* alltypes.h:219:14 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Id_t = uint32 /* alltypes.h:240:18 */

type Uid_t = uint32 /* alltypes.h:245:18 */

type Gid_t = uint32 /* alltypes.h:250:18 */

type Key_t = int32 /* alltypes.h:255:13 */

type Useconds_t = uint32 /* alltypes.h:260:18 */

type Pthread_t = uintptr /* alltypes.h:273:26 */

type Pthread_once_t = int32 /* alltypes.h:279:13 */

type Pthread_key_t = uint32 /* alltypes.h:284:18 */

type Pthread_spinlock_t = int32 /* alltypes.h:289:13 */

type Pthread_mutexattr_t = struct{ F__attr uint32 } /* alltypes.h:294:37 */

type Pthread_condattr_t = struct{ F__attr uint32 } /* alltypes.h:299:37 */

type Pthread_barrierattr_t = struct{ F__attr uint32 } /* alltypes.h:304:37 */

type Pthread_rwlockattr_t = struct{ F__attr [2]uint32 } /* alltypes.h:309:40 */

type Pthread_attr_t = struct {
	F__u struct {
		F__ccgo_pad1 [0]uint64
		F__i         [14]int32
	}
} /* alltypes.h:372:147 */

type Pthread_mutex_t = struct {
	F__u struct {
		F__ccgo_pad1 [0]uint64
		F__i         [10]int32
	}
} /* alltypes.h:377:157 */

type Pthread_cond_t = struct {
	F__u struct {
		F__ccgo_pad1 [0]uint64
		F__i         [12]int32
	}
} /* alltypes.h:387:112 */

type Pthread_rwlock_t = struct {
	F__u struct {
		F__ccgo_pad1 [0]uint64
		F__i         [14]int32
	}
} /* alltypes.h:397:139 */

type Pthread_barrier_t = struct {
	F__u struct {
		F__ccgo_pad1 [0]uint64
		F__i         [8]int32
	}
} /* alltypes.h:402:137 */

type U_int8_t = uint8   /* types.h:60:23 */
type U_int16_t = uint16 /* types.h:61:24 */
type U_int32_t = uint32 /* types.h:62:18 */
type Caddr_t = uintptr  /* types.h:63:14 */
type U_char = uint8     /* types.h:64:23 */
type U_short = uint16   /* types.h:65:24 */
type Ushort = uint16    /* types.h:65:33 */
type U_int = uint32     /* types.h:66:18 */
type Uint = uint32      /* types.h:66:25 */
type U_long = uint64    /* types.h:67:23 */
type Ulong = uint64     /* types.h:67:31 */
type Quad_t = int64     /* types.h:68:19 */
type U_quad_t = uint64  /* types.h:69:28 */

type Uint16_t = uint16 /* alltypes.h:126:25 */

type Uint32_t = uint32 /* alltypes.h:131:25 */

type Uint64_t = uint64 /* alltypes.h:136:25 */

type Timeval = struct {
	Ftv_sec  Time_t
	Ftv_usec Suseconds_t
} /* alltypes.h:224:1 */

type Timespec = struct {
	Ftv_sec  Time_t
	Ftv_nsec int64
} /* alltypes.h:229:1 */

type X__sigset_t = struct{ F__bits [16]uint64 } /* alltypes.h:349:9 */

type Sigset_t = X__sigset_t /* alltypes.h:349:71 */

type Fd_mask = uint64 /* select.h:20:23 */

type Fd_set = struct{ Ffds_bits [16]uint64 } /* select.h:24:3 */

var _ int8 /* gen.c:2:13: */
