// Code generated by 'ccgo dirent/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o dirent/dirent_linux_amd64.go -pkgname dirent -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package dirent

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	DT_BLK                 = 6   // dirent.h:45:1:
	DT_CHR                 = 2   // dirent.h:43:1:
	DT_DIR                 = 4   // dirent.h:44:1:
	DT_FIFO                = 1   // dirent.h:42:1:
	DT_LNK                 = 10  // dirent.h:47:1:
	DT_REG                 = 8   // dirent.h:46:1:
	DT_SOCK                = 12  // dirent.h:48:1:
	DT_UNKNOWN             = 0   // dirent.h:41:1:
	DT_WHT                 = 14  // dirent.h:49:1:
	FEATURES_H             = 0   // features.h:2:1:
	X_BSD_SOURCE           = 1   // features.h:15:1:
	X_DIRENT_H             = 0   // dirent.h:2:1:
	X_DIRENT_HAVE_D_OFF    = 0   // dirent.h:2:1:
	X_DIRENT_HAVE_D_RECLEN = 0   // dirent.h:1:1:
	X_DIRENT_HAVE_D_TYPE   = 0   // dirent.h:3:1:
	X_FEATURES_H           = 0   // features.h:2:1:
	X_FILE_OFFSET_BITS     = 64  // <builtin>:25:1:
	X_LP64                 = 1   // <predefined>:312:1:
	X_STDC_PREDEF_H        = 1   // <predefined>:174:1:
	X_XOPEN_SOURCE         = 700 // features.h:16:1:
	Linux                  = 1   // <predefined>:255:1:
	Unix                   = 1   // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Off_t = int64 /* alltypes.h:162:16 */

type Ino_t = uint64 /* alltypes.h:167:25 */

type Dirent = struct {
	Fd_ino       Ino_t
	Fd_off       Off_t
	Fd_reclen    uint16
	Fd_type      uint8
	Fd_name      [256]int8
	F__ccgo_pad1 [5]byte
} /* dirent.h:5:1 */

var _ int8 /* gen.c:2:13: */
