// Code generated by 'ccgo stdlib/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o stdlib/stdlib_linux_amd64.go -pkgname stdlib -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package stdlib

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	EXIT_FAILURE       = 1          // stdlib.h:76:1:
	EXIT_SUCCESS       = 0          // stdlib.h:77:1:
	FEATURES_H         = 0          // features.h:2:1:
	RAND_MAX           = 2147483647 // stdlib.h:82:1:
	STDLIB_H           = 0          // stdlib.h:2:1:
	WNOHANG            = 1          // stdlib.h:89:1:
	WUNTRACED          = 2          // stdlib.h:90:1:
	X_ALLOCA_H         = 0          // alloca.h:2:1:
	X_BSD_SOURCE       = 1          // features.h:15:1:
	X_FEATURES_H       = 0          // features.h:2:1:
	X_FILE_OFFSET_BITS = 64         // <builtin>:25:1:
	X_LP64             = 1          // <predefined>:312:1:
	X_STDC_PREDEF_H    = 1          // <predefined>:174:1:
	X_STDLIB_H         = 0          // stdlib.h:2:1:
	X_XOPEN_SOURCE     = 700        // features.h:16:1:
	Linux              = 1          // <predefined>:255:1:
	Unix               = 1          // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Div_t = struct {
	Fquot int32
	Frem  int32
} /* stdlib.h:62:35 */
type Ldiv_t = struct {
	Fquot int64
	Frem  int64
} /* stdlib.h:63:36 */
type Lldiv_t = struct {
	Fquot int64
	Frem  int64
} /* stdlib.h:64:41 */

var _ int8 /* gen.c:2:13: */
