// Code generated by 'ccgo fcntl/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o fcntl/fcntl_linux_amd64.go -pkgname fcntl -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package fcntl

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	AT_EACCESS             = 0x200      // fcntl.h:64:1:
	AT_EMPTY_PATH          = 0x1000     // fcntl.h:102:1:
	AT_FDCWD               = -100       // fcntl.h:60:1:
	AT_NO_AUTOMOUNT        = 0x800      // fcntl.h:101:1:
	AT_RECURSIVE           = 0x8000     // fcntl.h:107:1:
	AT_REMOVEDIR           = 0x200      // fcntl.h:62:1:
	AT_STATX_DONT_SYNC     = 0x4000     // fcntl.h:106:1:
	AT_STATX_FORCE_SYNC    = 0x2000     // fcntl.h:105:1:
	AT_STATX_SYNC_AS_STAT  = 0x0000     // fcntl.h:104:1:
	AT_STATX_SYNC_TYPE     = 0x6000     // fcntl.h:103:1:
	AT_SYMLINK_FOLLOW      = 0x400      // fcntl.h:63:1:
	AT_SYMLINK_NOFOLLOW    = 0x100      // fcntl.h:61:1:
	DN_ACCESS              = 0x00000001 // fcntl.h:151:1:
	DN_ATTRIB              = 0x00000020 // fcntl.h:156:1:
	DN_CREATE              = 0x00000004 // fcntl.h:153:1:
	DN_DELETE              = 0x00000008 // fcntl.h:154:1:
	DN_MODIFY              = 0x00000002 // fcntl.h:152:1:
	DN_MULTISHOT           = 0x80000000 // fcntl.h:157:1:
	DN_RENAME              = 0x00000010 // fcntl.h:155:1:
	FAPPEND                = 1024       // fcntl.h:109:1:
	FASYNC                 = 8192       // fcntl.h:111:1:
	FD_CLOEXEC             = 1          // fcntl.h:58:1:
	FEATURES_H             = 0          // features.h:2:1:
	FFSYNC                 = 1052672    // fcntl.h:110:1:
	FNDELAY                = 2048       // fcntl.h:113:1:
	FNONBLOCK              = 2048       // fcntl.h:112:1:
	F_ADD_SEALS            = 1033       // fcntl.h:130:1:
	F_CANCELLK             = 1029       // fcntl.h:127:1:
	F_DUPFD                = 0          // fcntl.h:22:1:
	F_DUPFD_CLOEXEC        = 1030       // fcntl.h:52:1:
	F_GETFD                = 1          // fcntl.h:23:1:
	F_GETFL                = 3          // fcntl.h:25:1:
	F_GETLEASE             = 1025       // fcntl.h:125:1:
	F_GETLK                = 5          // fcntl.h:33:1:
	F_GETOWN               = 9          // fcntl.h:29:1:
	F_GETOWNER_UIDS        = 17         // fcntl.h:40:1:
	F_GETOWN_EX            = 16         // fcntl.h:38:1:
	F_GETPIPE_SZ           = 1032       // fcntl.h:129:1:
	F_GETSIG               = 11         // fcntl.h:31:1:
	F_GET_FILE_RW_HINT     = 1037       // fcntl.h:141:1:
	F_GET_RW_HINT          = 1035       // fcntl.h:139:1:
	F_GET_SEALS            = 1034       // fcntl.h:131:1:
	F_LOCK                 = 1          // fcntl.h:120:1:
	F_NOTIFY               = 1026       // fcntl.h:126:1:
	F_OFD_GETLK            = 36         // fcntl.h:48:1:
	F_OFD_SETLK            = 37         // fcntl.h:49:1:
	F_OFD_SETLKW           = 38         // fcntl.h:50:1:
	F_OK                   = 0          // fcntl.h:115:1:
	F_RDLCK                = 0          // fcntl.h:54:1:
	F_SEAL_FUTURE_WRITE    = 0x0010     // fcntl.h:137:1:
	F_SEAL_GROW            = 0x0004     // fcntl.h:135:1:
	F_SEAL_SEAL            = 0x0001     // fcntl.h:133:1:
	F_SEAL_SHRINK          = 0x0002     // fcntl.h:134:1:
	F_SEAL_WRITE           = 0x0008     // fcntl.h:136:1:
	F_SETFD                = 2          // fcntl.h:24:1:
	F_SETFL                = 4          // fcntl.h:26:1:
	F_SETLEASE             = 1024       // fcntl.h:124:1:
	F_SETLK                = 6          // fcntl.h:34:1:
	F_SETLKW               = 7          // fcntl.h:35:1:
	F_SETOWN               = 8          // fcntl.h:28:1:
	F_SETOWN_EX            = 15         // fcntl.h:37:1:
	F_SETPIPE_SZ           = 1031       // fcntl.h:128:1:
	F_SETSIG               = 10         // fcntl.h:30:1:
	F_SET_FILE_RW_HINT     = 1038       // fcntl.h:142:1:
	F_SET_RW_HINT          = 1036       // fcntl.h:140:1:
	F_TEST                 = 3          // fcntl.h:122:1:
	F_TLOCK                = 2          // fcntl.h:121:1:
	F_ULOCK                = 0          // fcntl.h:119:1:
	F_UNLCK                = 2          // fcntl.h:56:1:
	F_WRLCK                = 1          // fcntl.h:55:1:
	O_ACCMODE              = 2097155    // fcntl.h:43:1:
	O_APPEND               = 02000      // fcntl.h:5:1:
	O_ASYNC                = 020000     // fcntl.h:14:1:
	O_CLOEXEC              = 02000000   // fcntl.h:12:1:
	O_CREAT                = 0100       // fcntl.h:1:1:
	O_DIRECT               = 040000     // fcntl.h:15:1:
	O_DIRECTORY            = 0200000    // fcntl.h:10:1:
	O_DSYNC                = 010000     // fcntl.h:7:1:
	O_EXCL                 = 0200       // fcntl.h:2:1:
	O_EXEC                 = 2097152    // fcntl.h:40:1:
	O_LARGEFILE            = 0          // fcntl.h:16:1:
	O_NDELAY               = 2048       // fcntl.h:20:1:
	O_NOATIME              = 01000000   // fcntl.h:17:1:
	O_NOCTTY               = 0400       // fcntl.h:3:1:
	O_NOFOLLOW             = 0400000    // fcntl.h:11:1:
	O_NONBLOCK             = 04000      // fcntl.h:6:1:
	O_PATH                 = 010000000  // fcntl.h:18:1:
	O_RDONLY               = 00         // fcntl.h:44:1:
	O_RDWR                 = 02         // fcntl.h:46:1:
	O_RSYNC                = 04010000   // fcntl.h:9:1:
	O_SEARCH               = 2097152    // fcntl.h:39:1:
	O_SYNC                 = 04010000   // fcntl.h:8:1:
	O_TMPFILE              = 020200000  // fcntl.h:19:1:
	O_TRUNC                = 01000      // fcntl.h:4:1:
	O_TTY_INIT             = 0          // fcntl.h:41:1:
	O_WRONLY               = 01         // fcntl.h:45:1:
	POSIX_FADV_DONTNEED    = 4          // fcntl.h:71:1:
	POSIX_FADV_NOREUSE     = 5          // fcntl.h:72:1:
	POSIX_FADV_NORMAL      = 0          // fcntl.h:66:1:
	POSIX_FADV_RANDOM      = 1          // fcntl.h:67:1:
	POSIX_FADV_SEQUENTIAL  = 2          // fcntl.h:68:1:
	POSIX_FADV_WILLNEED    = 3          // fcntl.h:69:1:
	RWF_WRITE_LIFE_NOT_SET = 0          // fcntl.h:144:1:
	RWH_WRITE_LIFE_EXTREME = 5          // fcntl.h:149:1:
	RWH_WRITE_LIFE_LONG    = 4          // fcntl.h:148:1:
	RWH_WRITE_LIFE_MEDIUM  = 3          // fcntl.h:147:1:
	RWH_WRITE_LIFE_NONE    = 1          // fcntl.h:145:1:
	RWH_WRITE_LIFE_SHORT   = 2          // fcntl.h:146:1:
	R_OK                   = 4          // fcntl.h:116:1:
	SEEK_CUR               = 1          // fcntl.h:79:1:
	SEEK_END               = 2          // fcntl.h:80:1:
	SEEK_SET               = 0          // fcntl.h:78:1:
	S_IRGRP                = 0040       // fcntl.h:90:1:
	S_IROTH                = 0004       // fcntl.h:94:1:
	S_IRUSR                = 0400       // fcntl.h:86:1:
	S_IRWXG                = 0070       // fcntl.h:93:1:
	S_IRWXO                = 0007       // fcntl.h:97:1:
	S_IRWXU                = 0700       // fcntl.h:89:1:
	S_ISGID                = 02000      // fcntl.h:84:1:
	S_ISUID                = 04000      // fcntl.h:83:1:
	S_ISVTX                = 01000      // fcntl.h:85:1:
	S_IWGRP                = 0020       // fcntl.h:91:1:
	S_IWOTH                = 0002       // fcntl.h:95:1:
	S_IWUSR                = 0200       // fcntl.h:87:1:
	S_IXGRP                = 0010       // fcntl.h:92:1:
	S_IXOTH                = 0001       // fcntl.h:96:1:
	S_IXUSR                = 0100       // fcntl.h:88:1:
	W_OK                   = 2          // fcntl.h:117:1:
	X_OK                   = 1          // fcntl.h:118:1:
	X_BSD_SOURCE           = 1          // features.h:15:1:
	X_FCNTL_H              = 0          // fcntl.h:2:1:
	X_FEATURES_H           = 0          // features.h:2:1:
	X_FILE_OFFSET_BITS     = 64         // <builtin>:25:1:
	X_LP64                 = 1          // <predefined>:312:1:
	X_STDC_PREDEF_H        = 1          // <predefined>:174:1:
	X_XOPEN_SOURCE         = 700        // features.h:16:1:
	Linux                  = 1          // <predefined>:255:1:
	Unix                   = 1          // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Mode_t = uint32 /* alltypes.h:152:18 */

type Off_t = int64 /* alltypes.h:162:16 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Flock = struct {
	Fl_type      int16
	Fl_whence    int16
	F__ccgo_pad1 [4]byte
	Fl_start     Off_t
	Fl_len       Off_t
	Fl_pid       Pid_t
	F__ccgo_pad2 [4]byte
} /* fcntl.h:24:1 */

var _ int8 /* gen.c:2:13: */
