// Code generated by 'ccgo sys/vfs/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o sys/vfs/vfs_linux_amd64.go -pkgname vfs -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package vfs

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	FEATURES_H         = 0    // features.h:2:1:
	ST_APPEND          = 256  // statvfs.h:39:1:
	ST_IMMUTABLE       = 512  // statvfs.h:40:1:
	ST_MANDLOCK        = 64   // statvfs.h:37:1:
	ST_NOATIME         = 1024 // statvfs.h:41:1:
	ST_NODEV           = 4    // statvfs.h:34:1:
	ST_NODIRATIME      = 2048 // statvfs.h:42:1:
	ST_NOEXEC          = 8    // statvfs.h:35:1:
	ST_NOSUID          = 2    // statvfs.h:33:1:
	ST_RDONLY          = 1    // statvfs.h:32:1:
	ST_RELATIME        = 4096 // statvfs.h:43:1:
	ST_SYNCHRONOUS     = 16   // statvfs.h:36:1:
	ST_WRITE           = 128  // statvfs.h:38:1:
	X_BSD_SOURCE       = 1    // features.h:15:1:
	X_FEATURES_H       = 0    // features.h:2:1:
	X_FILE_OFFSET_BITS = 64   // <builtin>:25:1:
	X_LP64             = 1    // <predefined>:312:1:
	X_STDC_PREDEF_H    = 1    // <predefined>:174:1:
	X_SYS_STATFS_H     = 0    // statfs.h:2:1:
	X_SYS_STATVFS_H    = 0    // statvfs.h:2:1:
	X_XOPEN_SOURCE     = 700  // features.h:16:1:
	Linux              = 1    // <predefined>:255:1:
	Unix               = 1    // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Fsblkcnt_t = uint64 /* alltypes.h:187:25 */

type Fsfilcnt_t = uint64 /* alltypes.h:192:25 */

type Statvfs = struct {
	Ff_bsize    uint64
	Ff_frsize   uint64
	Ff_blocks   Fsblkcnt_t
	Ff_bfree    Fsblkcnt_t
	Ff_bavail   Fsblkcnt_t
	Ff_files    Fsfilcnt_t
	Ff_ffree    Fsfilcnt_t
	Ff_favail   Fsfilcnt_t
	Ff_fsid     uint64
	Ff_flag     uint64
	Ff_namemax  uint64
	F__reserved [6]int32
} /* statvfs.h:14:1 */

type X__fsid_t = struct{ F__val [2]int32 } /* statfs.h:12:9 */

type Fsid_t = X__fsid_t /* statfs.h:14:3 */

type Statfs = struct {
	Ff_type    uint64
	Ff_bsize   uint64
	Ff_blocks  Fsblkcnt_t
	Ff_bfree   Fsblkcnt_t
	Ff_bavail  Fsblkcnt_t
	Ff_files   Fsfilcnt_t
	Ff_ffree   Fsfilcnt_t
	Ff_fsid    Fsid_t
	Ff_namelen uint64
	Ff_frsize  uint64
	Ff_flags   uint64
	Ff_spare   [4]uint64
} /* statfs.h:1:1 */

var _ int8 /* gen.c:2:13: */
