// Code generated by 'ccgo netdb/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o netdb/netdb_linux_amd64.go -pkgname netdb -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package netdb

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	AF_ALG                           = 38                   // socket.h:190:1:
	AF_APPLETALK                     = 5                    // socket.h:156:1:
	AF_ASH                           = 18                   // socket.h:170:1:
	AF_ATMPVC                        = 8                    // socket.h:159:1:
	AF_ATMSVC                        = 20                   // socket.h:172:1:
	AF_AX25                          = 3                    // socket.h:154:1:
	AF_BLUETOOTH                     = 31                   // socket.h:183:1:
	AF_BRIDGE                        = 7                    // socket.h:158:1:
	AF_CAIF                          = 37                   // socket.h:189:1:
	AF_CAN                           = 29                   // socket.h:181:1:
	AF_DECnet                        = 12                   // socket.h:163:1:
	AF_ECONET                        = 19                   // socket.h:171:1:
	AF_FILE                          = 1                    // socket.h:152:1:
	AF_IB                            = 27                   // socket.h:179:1:
	AF_IEEE802154                    = 36                   // socket.h:188:1:
	AF_INET                          = 2                    // socket.h:153:1:
	AF_INET6                         = 10                   // socket.h:161:1:
	AF_IPX                           = 4                    // socket.h:155:1:
	AF_IRDA                          = 23                   // socket.h:175:1:
	AF_ISDN                          = 34                   // socket.h:186:1:
	AF_IUCV                          = 32                   // socket.h:184:1:
	AF_KCM                           = 41                   // socket.h:193:1:
	AF_KEY                           = 15                   // socket.h:166:1:
	AF_LLC                           = 26                   // socket.h:178:1:
	AF_LOCAL                         = 1                    // socket.h:150:1:
	AF_MAX                           = 45                   // socket.h:197:1:
	AF_MPLS                          = 28                   // socket.h:180:1:
	AF_NETBEUI                       = 13                   // socket.h:164:1:
	AF_NETLINK                       = 16                   // socket.h:167:1:
	AF_NETROM                        = 6                    // socket.h:157:1:
	AF_NFC                           = 39                   // socket.h:191:1:
	AF_PACKET                        = 17                   // socket.h:169:1:
	AF_PHONET                        = 35                   // socket.h:187:1:
	AF_PPPOX                         = 24                   // socket.h:176:1:
	AF_QIPCRTR                       = 42                   // socket.h:194:1:
	AF_RDS                           = 21                   // socket.h:173:1:
	AF_ROSE                          = 11                   // socket.h:162:1:
	AF_ROUTE                         = 16                   // socket.h:168:1:
	AF_RXRPC                         = 33                   // socket.h:185:1:
	AF_SECURITY                      = 14                   // socket.h:165:1:
	AF_SMC                           = 43                   // socket.h:195:1:
	AF_SNA                           = 22                   // socket.h:174:1:
	AF_TIPC                          = 30                   // socket.h:182:1:
	AF_UNIX                          = 1                    // socket.h:151:1:
	AF_UNSPEC                        = 0                    // socket.h:149:1:
	AF_VSOCK                         = 40                   // socket.h:192:1:
	AF_WANPIPE                       = 25                   // socket.h:177:1:
	AF_X25                           = 9                    // socket.h:160:1:
	AF_XDP                           = 44                   // socket.h:196:1:
	AI_ADDRCONFIG                    = 0x20                 // netdb.h:32:1:
	AI_ALL                           = 0x10                 // netdb.h:31:1:
	AI_CANONNAME                     = 0x02                 // netdb.h:28:1:
	AI_NUMERICHOST                   = 0x04                 // netdb.h:29:1:
	AI_NUMERICSERV                   = 0x400                // netdb.h:33:1:
	AI_PASSIVE                       = 0x01                 // netdb.h:27:1:
	AI_V4MAPPED                      = 0x08                 // netdb.h:30:1:
	EAI_ADDRFAMILY                   = -9                   // netdb.h:140:1:
	EAI_AGAIN                        = -3                   // netdb.h:45:1:
	EAI_ALLDONE                      = -103                 // netdb.h:144:1:
	EAI_BADFLAGS                     = -1                   // netdb.h:43:1:
	EAI_CANCELED                     = -101                 // netdb.h:142:1:
	EAI_FAIL                         = -4                   // netdb.h:46:1:
	EAI_FAMILY                       = -6                   // netdb.h:47:1:
	EAI_IDN_ENCODE                   = -105                 // netdb.h:146:1:
	EAI_INPROGRESS                   = -100                 // netdb.h:141:1:
	EAI_INTR                         = -104                 // netdb.h:145:1:
	EAI_MEMORY                       = -10                  // netdb.h:50:1:
	EAI_NODATA                       = -5                   // netdb.h:139:1:
	EAI_NONAME                       = -2                   // netdb.h:44:1:
	EAI_NOTCANCELED                  = -102                 // netdb.h:143:1:
	EAI_OVERFLOW                     = -12                  // netdb.h:52:1:
	EAI_SERVICE                      = -8                   // netdb.h:49:1:
	EAI_SOCKTYPE                     = -7                   // netdb.h:48:1:
	EAI_SYSTEM                       = -11                  // netdb.h:51:1:
	FEATURES_H                       = 0                    // features.h:2:1:
	HOST_NOT_FOUND                   = 1                    // netdb.h:123:1:
	INET6_ADDRSTRLEN                 = 46                   // in.h:64:1:
	INET_ADDRSTRLEN                  = 16                   // in.h:63:1:
	INT16_MAX                        = 32767                // stdint.h:44:1:
	INT16_MIN                        = -32768               // stdint.h:39:1:
	INT32_MAX                        = 2147483647           // stdint.h:45:1:
	INT32_MIN                        = -2147483648          // stdint.h:40:1:
	INT64_MAX                        = 9223372036854775807  // stdint.h:46:1:
	INT64_MIN                        = -9223372036854775808 // stdint.h:41:1:
	INT8_MAX                         = 127                  // stdint.h:43:1:
	INT8_MIN                         = -128                 // stdint.h:38:1:
	INTMAX_MAX                       = 9223372036854775807  // stdint.h:78:1:
	INTMAX_MIN                       = -9223372036854775808 // stdint.h:77:1:
	INTPTR_MAX                       = 9223372036854775807  // stdint.h:16:1:
	INTPTR_MIN                       = -9223372036854775808 // stdint.h:15:1:
	INT_FAST16_MAX                   = 2147483647           // stdint.h:9:1:
	INT_FAST16_MIN                   = -2147483648          // stdint.h:6:1:
	INT_FAST32_MAX                   = 2147483647           // stdint.h:10:1:
	INT_FAST32_MIN                   = -2147483648          // stdint.h:7:1:
	INT_FAST64_MAX                   = 9223372036854775807  // stdint.h:62:1:
	INT_FAST64_MIN                   = -9223372036854775808 // stdint.h:54:1:
	INT_FAST8_MAX                    = 127                  // stdint.h:61:1:
	INT_FAST8_MIN                    = -128                 // stdint.h:53:1:
	INT_LEAST16_MAX                  = 32767                // stdint.h:65:1:
	INT_LEAST16_MIN                  = -32768               // stdint.h:57:1:
	INT_LEAST32_MAX                  = 2147483647           // stdint.h:66:1:
	INT_LEAST32_MIN                  = -2147483648          // stdint.h:58:1:
	INT_LEAST64_MAX                  = 9223372036854775807  // stdint.h:67:1:
	INT_LEAST64_MIN                  = -9223372036854775808 // stdint.h:59:1:
	INT_LEAST8_MAX                   = 127                  // stdint.h:64:1:
	INT_LEAST8_MIN                   = -128                 // stdint.h:56:1:
	IN_CLASSA_HOST                   = 16777215             // in.h:157:1:
	IN_CLASSA_MAX                    = 128                  // in.h:158:1:
	IN_CLASSA_NET                    = 0xff000000           // in.h:155:1:
	IN_CLASSA_NSHIFT                 = 24                   // in.h:156:1:
	IN_CLASSB_HOST                   = 65535                // in.h:162:1:
	IN_CLASSB_MAX                    = 65536                // in.h:163:1:
	IN_CLASSB_NET                    = 0xffff0000           // in.h:160:1:
	IN_CLASSB_NSHIFT                 = 16                   // in.h:161:1:
	IN_CLASSC_HOST                   = 255                  // in.h:167:1:
	IN_CLASSC_NET                    = 0xffffff00           // in.h:165:1:
	IN_CLASSC_NSHIFT                 = 8                    // in.h:166:1:
	IN_LOOPBACKNET                   = 127                  // in.h:173:1:
	IPPORT_RESERVED                  = 1024                 // in.h:71:1:
	IPPROTO_AH                       = 51                   // in.h:91:1:
	IPPROTO_BEETPH                   = 94                   // in.h:96:1:
	IPPROTO_COMP                     = 108                  // in.h:99:1:
	IPPROTO_DCCP                     = 33                   // in.h:84:1:
	IPPROTO_DSTOPTS                  = 60                   // in.h:94:1:
	IPPROTO_EGP                      = 8                    // in.h:79:1:
	IPPROTO_ENCAP                    = 98                   // in.h:97:1:
	IPPROTO_ESP                      = 50                   // in.h:90:1:
	IPPROTO_FRAGMENT                 = 44                   // in.h:87:1:
	IPPROTO_GRE                      = 47                   // in.h:89:1:
	IPPROTO_HOPOPTS                  = 0                    // in.h:74:1:
	IPPROTO_ICMP                     = 1                    // in.h:75:1:
	IPPROTO_ICMPV6                   = 58                   // in.h:92:1:
	IPPROTO_IDP                      = 22                   // in.h:82:1:
	IPPROTO_IGMP                     = 2                    // in.h:76:1:
	IPPROTO_IP                       = 0                    // in.h:73:1:
	IPPROTO_IPIP                     = 4                    // in.h:77:1:
	IPPROTO_IPV6                     = 41                   // in.h:85:1:
	IPPROTO_MAX                      = 256                  // in.h:105:1:
	IPPROTO_MH                       = 135                  // in.h:101:1:
	IPPROTO_MPLS                     = 137                  // in.h:103:1:
	IPPROTO_MTP                      = 92                   // in.h:95:1:
	IPPROTO_NONE                     = 59                   // in.h:93:1:
	IPPROTO_PIM                      = 103                  // in.h:98:1:
	IPPROTO_PUP                      = 12                   // in.h:80:1:
	IPPROTO_RAW                      = 255                  // in.h:104:1:
	IPPROTO_ROUTING                  = 43                   // in.h:86:1:
	IPPROTO_RSVP                     = 46                   // in.h:88:1:
	IPPROTO_SCTP                     = 132                  // in.h:100:1:
	IPPROTO_TCP                      = 6                    // in.h:78:1:
	IPPROTO_TP                       = 29                   // in.h:83:1:
	IPPROTO_UDP                      = 17                   // in.h:81:1:
	IPPROTO_UDPLITE                  = 136                  // in.h:102:1:
	IPV6_2292DSTOPTS                 = 4                    // in.h:317:1:
	IPV6_2292HOPLIMIT                = 8                    // in.h:321:1:
	IPV6_2292HOPOPTS                 = 3                    // in.h:316:1:
	IPV6_2292PKTINFO                 = 2                    // in.h:315:1:
	IPV6_2292PKTOPTIONS              = 6                    // in.h:319:1:
	IPV6_2292RTHDR                   = 5                    // in.h:318:1:
	IPV6_ADDRFORM                    = 1                    // in.h:314:1:
	IPV6_ADDR_PREFERENCES            = 72                   // in.h:360:1:
	IPV6_ADD_MEMBERSHIP              = 20                   // in.h:369:1:
	IPV6_AUTHHDR                     = 10                   // in.h:323:1:
	IPV6_AUTOFLOWLABEL               = 70                   // in.h:359:1:
	IPV6_CHECKSUM                    = 7                    // in.h:320:1:
	IPV6_DONTFRAG                    = 62                   // in.h:356:1:
	IPV6_DROP_MEMBERSHIP             = 21                   // in.h:370:1:
	IPV6_DSTOPTS                     = 59                   // in.h:353:1:
	IPV6_FREEBIND                    = 78                   // in.h:367:1:
	IPV6_HDRINCL                     = 36                   // in.h:341:1:
	IPV6_HOPLIMIT                    = 52                   // in.h:346:1:
	IPV6_HOPOPTS                     = 54                   // in.h:348:1:
	IPV6_IPSEC_POLICY                = 34                   // in.h:339:1:
	IPV6_JOIN_ANYCAST                = 27                   // in.h:335:1:
	IPV6_JOIN_GROUP                  = 20                   // in.h:328:1:
	IPV6_LEAVE_ANYCAST               = 28                   // in.h:336:1:
	IPV6_LEAVE_GROUP                 = 21                   // in.h:329:1:
	IPV6_MINHOPCOUNT                 = 73                   // in.h:361:1:
	IPV6_MTU                         = 24                   // in.h:332:1:
	IPV6_MTU_DISCOVER                = 23                   // in.h:331:1:
	IPV6_MULTICAST_ALL               = 29                   // in.h:337:1:
	IPV6_MULTICAST_HOPS              = 18                   // in.h:326:1:
	IPV6_MULTICAST_IF                = 17                   // in.h:325:1:
	IPV6_MULTICAST_LOOP              = 19                   // in.h:327:1:
	IPV6_NEXTHOP                     = 9                    // in.h:322:1:
	IPV6_ORIGDSTADDR                 = 74                   // in.h:362:1:
	IPV6_PATHMTU                     = 61                   // in.h:355:1:
	IPV6_PKTINFO                     = 50                   // in.h:344:1:
	IPV6_PMTUDISC_DO                 = 2                    // in.h:376:1:
	IPV6_PMTUDISC_DONT               = 0                    // in.h:374:1:
	IPV6_PMTUDISC_INTERFACE          = 4                    // in.h:378:1:
	IPV6_PMTUDISC_OMIT               = 5                    // in.h:379:1:
	IPV6_PMTUDISC_PROBE              = 3                    // in.h:377:1:
	IPV6_PMTUDISC_WANT               = 1                    // in.h:375:1:
	IPV6_PREFER_SRC_CGA              = 0x0008               // in.h:386:1:
	IPV6_PREFER_SRC_COA              = 0x0004               // in.h:384:1:
	IPV6_PREFER_SRC_HOME             = 0x0400               // in.h:385:1:
	IPV6_PREFER_SRC_NONCGA           = 0x0800               // in.h:387:1:
	IPV6_PREFER_SRC_PUBLIC           = 0x0002               // in.h:382:1:
	IPV6_PREFER_SRC_PUBTMP_DEFAULT   = 0x0100               // in.h:383:1:
	IPV6_PREFER_SRC_TMP              = 0x0001               // in.h:381:1:
	IPV6_RECVDSTOPTS                 = 58                   // in.h:352:1:
	IPV6_RECVERR                     = 25                   // in.h:333:1:
	IPV6_RECVFRAGSIZE                = 77                   // in.h:366:1:
	IPV6_RECVHOPLIMIT                = 51                   // in.h:345:1:
	IPV6_RECVHOPOPTS                 = 53                   // in.h:347:1:
	IPV6_RECVORIGDSTADDR             = 74                   // in.h:363:1:
	IPV6_RECVPATHMTU                 = 60                   // in.h:354:1:
	IPV6_RECVPKTINFO                 = 49                   // in.h:343:1:
	IPV6_RECVRTHDR                   = 56                   // in.h:350:1:
	IPV6_RECVTCLASS                  = 66                   // in.h:357:1:
	IPV6_ROUTER_ALERT                = 22                   // in.h:330:1:
	IPV6_ROUTER_ALERT_ISOLATE        = 30                   // in.h:338:1:
	IPV6_RTHDR                       = 57                   // in.h:351:1:
	IPV6_RTHDRDSTOPTS                = 55                   // in.h:349:1:
	IPV6_RTHDR_LOOSE                 = 0                    // in.h:389:1:
	IPV6_RTHDR_STRICT                = 1                    // in.h:390:1:
	IPV6_RTHDR_TYPE_0                = 0                    // in.h:392:1:
	IPV6_RXDSTOPTS                   = 59                   // in.h:372:1:
	IPV6_RXHOPOPTS                   = 54                   // in.h:371:1:
	IPV6_TCLASS                      = 67                   // in.h:358:1:
	IPV6_TRANSPARENT                 = 75                   // in.h:364:1:
	IPV6_UNICAST_HOPS                = 16                   // in.h:324:1:
	IPV6_UNICAST_IF                  = 76                   // in.h:365:1:
	IPV6_V6ONLY                      = 26                   // in.h:334:1:
	IPV6_XFRM_POLICY                 = 35                   // in.h:340:1:
	IP_ADD_MEMBERSHIP                = 35                   // in.h:206:1:
	IP_ADD_SOURCE_MEMBERSHIP         = 39                   // in.h:210:1:
	IP_BIND_ADDRESS_NO_PORT          = 24                   // in.h:201:1:
	IP_BLOCK_SOURCE                  = 38                   // in.h:209:1:
	IP_CHECKSUM                      = 23                   // in.h:200:1:
	IP_DEFAULT_MULTICAST_LOOP        = 1                    // in.h:226:1:
	IP_DEFAULT_MULTICAST_TTL         = 1                    // in.h:225:1:
	IP_DROP_MEMBERSHIP               = 36                   // in.h:207:1:
	IP_DROP_SOURCE_MEMBERSHIP        = 40                   // in.h:211:1:
	IP_FREEBIND                      = 15                   // in.h:191:1:
	IP_HDRINCL                       = 3                    // in.h:178:1:
	IP_IPSEC_POLICY                  = 16                   // in.h:192:1:
	IP_MAX_MEMBERSHIPS               = 20                   // in.h:227:1:
	IP_MINTTL                        = 21                   // in.h:198:1:
	IP_MSFILTER                      = 41                   // in.h:212:1:
	IP_MTU                           = 14                   // in.h:190:1:
	IP_MTU_DISCOVER                  = 10                   // in.h:186:1:
	IP_MULTICAST_ALL                 = 49                   // in.h:213:1:
	IP_MULTICAST_IF                  = 32                   // in.h:203:1:
	IP_MULTICAST_LOOP                = 34                   // in.h:205:1:
	IP_MULTICAST_TTL                 = 33                   // in.h:204:1:
	IP_NODEFRAG                      = 22                   // in.h:199:1:
	IP_OPTIONS                       = 4                    // in.h:179:1:
	IP_ORIGDSTADDR                   = 20                   // in.h:196:1:
	IP_PASSSEC                       = 18                   // in.h:194:1:
	IP_PKTINFO                       = 8                    // in.h:183:1:
	IP_PKTOPTIONS                    = 9                    // in.h:184:1:
	IP_PMTUDISC                      = 10                   // in.h:185:1:
	IP_PMTUDISC_DO                   = 2                    // in.h:220:1:
	IP_PMTUDISC_DONT                 = 0                    // in.h:218:1:
	IP_PMTUDISC_INTERFACE            = 4                    // in.h:222:1:
	IP_PMTUDISC_OMIT                 = 5                    // in.h:223:1:
	IP_PMTUDISC_PROBE                = 3                    // in.h:221:1:
	IP_PMTUDISC_WANT                 = 1                    // in.h:219:1:
	IP_RECVERR                       = 11                   // in.h:187:1:
	IP_RECVFRAGSIZE                  = 25                   // in.h:202:1:
	IP_RECVOPTS                      = 6                    // in.h:181:1:
	IP_RECVORIGDSTADDR               = 20                   // in.h:197:1:
	IP_RECVRETOPTS                   = 7                    // in.h:216:1:
	IP_RECVTOS                       = 13                   // in.h:189:1:
	IP_RECVTTL                       = 12                   // in.h:188:1:
	IP_RETOPTS                       = 7                    // in.h:182:1:
	IP_ROUTER_ALERT                  = 5                    // in.h:180:1:
	IP_TOS                           = 1                    // in.h:176:1:
	IP_TRANSPARENT                   = 19                   // in.h:195:1:
	IP_TTL                           = 2                    // in.h:177:1:
	IP_UNBLOCK_SOURCE                = 37                   // in.h:208:1:
	IP_UNICAST_IF                    = 50                   // in.h:214:1:
	IP_XFRM_POLICY                   = 17                   // in.h:193:1:
	MCAST_BLOCK_SOURCE               = 43                   // in.h:237:1:
	MCAST_EXCLUDE                    = 0                    // in.h:244:1:
	MCAST_INCLUDE                    = 1                    // in.h:245:1:
	MCAST_JOIN_GROUP                 = 42                   // in.h:236:1:
	MCAST_JOIN_SOURCE_GROUP          = 46                   // in.h:240:1:
	MCAST_LEAVE_GROUP                = 45                   // in.h:239:1:
	MCAST_LEAVE_SOURCE_GROUP         = 47                   // in.h:241:1:
	MCAST_MSFILTER                   = 48                   // in.h:242:1:
	MCAST_UNBLOCK_SOURCE             = 44                   // in.h:238:1:
	MSG_BATCH                        = 0x40000              // socket.h:345:1:
	MSG_CMSG_CLOEXEC                 = 0x40000000           // socket.h:348:1:
	MSG_CONFIRM                      = 0x0800               // socket.h:339:1:
	MSG_CTRUNC                       = 0x0008               // socket.h:331:1:
	MSG_DONTROUTE                    = 0x0004               // socket.h:330:1:
	MSG_DONTWAIT                     = 0x0040               // socket.h:334:1:
	MSG_EOR                          = 0x0080               // socket.h:335:1:
	MSG_ERRQUEUE                     = 0x2000               // socket.h:341:1:
	MSG_FASTOPEN                     = 0x20000000           // socket.h:347:1:
	MSG_FIN                          = 0x0200               // socket.h:337:1:
	MSG_MORE                         = 0x8000               // socket.h:343:1:
	MSG_NOSIGNAL                     = 0x4000               // socket.h:342:1:
	MSG_OOB                          = 0x0001               // socket.h:328:1:
	MSG_PEEK                         = 0x0002               // socket.h:329:1:
	MSG_PROXY                        = 0x0010               // socket.h:332:1:
	MSG_RST                          = 0x1000               // socket.h:340:1:
	MSG_SYN                          = 0x0400               // socket.h:338:1:
	MSG_TRUNC                        = 0x0020               // socket.h:333:1:
	MSG_WAITALL                      = 0x0100               // socket.h:336:1:
	MSG_WAITFORONE                   = 0x10000              // socket.h:344:1:
	MSG_ZEROCOPY                     = 0x4000000            // socket.h:346:1:
	NI_DGRAM                         = 0x10                 // netdb.h:40:1:
	NI_MAXHOST                       = 255                  // netdb.h:147:1:
	NI_MAXSERV                       = 32                   // netdb.h:148:1:
	NI_NAMEREQD                      = 0x08                 // netdb.h:39:1:
	NI_NOFQDN                        = 0x04                 // netdb.h:38:1:
	NI_NUMERICHOST                   = 0x01                 // netdb.h:36:1:
	NI_NUMERICSCOPE                  = 0x100                // netdb.h:41:1:
	NI_NUMERICSERV                   = 0x02                 // netdb.h:37:1:
	NO_ADDRESS                       = 4                    // netdb.h:127:1:
	NO_DATA                          = 4                    // netdb.h:126:1:
	NO_RECOVERY                      = 3                    // netdb.h:125:1:
	PF_ALG                           = 38                   // socket.h:140:1:
	PF_APPLETALK                     = 5                    // socket.h:106:1:
	PF_ASH                           = 18                   // socket.h:120:1:
	PF_ATMPVC                        = 8                    // socket.h:109:1:
	PF_ATMSVC                        = 20                   // socket.h:122:1:
	PF_AX25                          = 3                    // socket.h:104:1:
	PF_BLUETOOTH                     = 31                   // socket.h:133:1:
	PF_BRIDGE                        = 7                    // socket.h:108:1:
	PF_CAIF                          = 37                   // socket.h:139:1:
	PF_CAN                           = 29                   // socket.h:131:1:
	PF_DECnet                        = 12                   // socket.h:113:1:
	PF_ECONET                        = 19                   // socket.h:121:1:
	PF_FILE                          = 1                    // socket.h:102:1:
	PF_IB                            = 27                   // socket.h:129:1:
	PF_IEEE802154                    = 36                   // socket.h:138:1:
	PF_INET                          = 2                    // socket.h:103:1:
	PF_INET6                         = 10                   // socket.h:111:1:
	PF_IPX                           = 4                    // socket.h:105:1:
	PF_IRDA                          = 23                   // socket.h:125:1:
	PF_ISDN                          = 34                   // socket.h:136:1:
	PF_IUCV                          = 32                   // socket.h:134:1:
	PF_KCM                           = 41                   // socket.h:143:1:
	PF_KEY                           = 15                   // socket.h:116:1:
	PF_LLC                           = 26                   // socket.h:128:1:
	PF_LOCAL                         = 1                    // socket.h:100:1:
	PF_MAX                           = 45                   // socket.h:147:1:
	PF_MPLS                          = 28                   // socket.h:130:1:
	PF_NETBEUI                       = 13                   // socket.h:114:1:
	PF_NETLINK                       = 16                   // socket.h:117:1:
	PF_NETROM                        = 6                    // socket.h:107:1:
	PF_NFC                           = 39                   // socket.h:141:1:
	PF_PACKET                        = 17                   // socket.h:119:1:
	PF_PHONET                        = 35                   // socket.h:137:1:
	PF_PPPOX                         = 24                   // socket.h:126:1:
	PF_QIPCRTR                       = 42                   // socket.h:144:1:
	PF_RDS                           = 21                   // socket.h:123:1:
	PF_ROSE                          = 11                   // socket.h:112:1:
	PF_ROUTE                         = 16                   // socket.h:118:1:
	PF_RXRPC                         = 33                   // socket.h:135:1:
	PF_SECURITY                      = 14                   // socket.h:115:1:
	PF_SMC                           = 43                   // socket.h:145:1:
	PF_SNA                           = 22                   // socket.h:124:1:
	PF_TIPC                          = 30                   // socket.h:132:1:
	PF_UNIX                          = 1                    // socket.h:101:1:
	PF_UNSPEC                        = 0                    // socket.h:99:1:
	PF_VSOCK                         = 40                   // socket.h:142:1:
	PF_WANPIPE                       = 25                   // socket.h:127:1:
	PF_X25                           = 9                    // socket.h:110:1:
	PF_XDP                           = 44                   // socket.h:146:1:
	PRIX16                           = "X"                  // inttypes.h:109:1:
	PRIX32                           = "X"                  // inttypes.h:110:1:
	PRIX8                            = "X"                  // inttypes.h:108:1:
	PRIXFAST16                       = "X"                  // inttypes.h:119:1:
	PRIXFAST32                       = "X"                  // inttypes.h:120:1:
	PRIXFAST8                        = "X"                  // inttypes.h:118:1:
	PRIXLEAST16                      = "X"                  // inttypes.h:114:1:
	PRIXLEAST32                      = "X"                  // inttypes.h:115:1:
	PRIXLEAST8                       = "X"                  // inttypes.h:113:1:
	PRId16                           = "d"                  // inttypes.h:34:1:
	PRId32                           = "d"                  // inttypes.h:35:1:
	PRId8                            = "d"                  // inttypes.h:33:1:
	PRIdFAST16                       = "d"                  // inttypes.h:44:1:
	PRIdFAST32                       = "d"                  // inttypes.h:45:1:
	PRIdFAST8                        = "d"                  // inttypes.h:43:1:
	PRIdLEAST16                      = "d"                  // inttypes.h:39:1:
	PRIdLEAST32                      = "d"                  // inttypes.h:40:1:
	PRIdLEAST8                       = "d"                  // inttypes.h:38:1:
	PRIi16                           = "i"                  // inttypes.h:49:1:
	PRIi32                           = "i"                  // inttypes.h:50:1:
	PRIi8                            = "i"                  // inttypes.h:48:1:
	PRIiFAST16                       = "i"                  // inttypes.h:59:1:
	PRIiFAST32                       = "i"                  // inttypes.h:60:1:
	PRIiFAST8                        = "i"                  // inttypes.h:58:1:
	PRIiLEAST16                      = "i"                  // inttypes.h:54:1:
	PRIiLEAST32                      = "i"                  // inttypes.h:55:1:
	PRIiLEAST8                       = "i"                  // inttypes.h:53:1:
	PRIo16                           = "o"                  // inttypes.h:64:1:
	PRIo32                           = "o"                  // inttypes.h:65:1:
	PRIo8                            = "o"                  // inttypes.h:63:1:
	PRIoFAST16                       = "o"                  // inttypes.h:74:1:
	PRIoFAST32                       = "o"                  // inttypes.h:75:1:
	PRIoFAST8                        = "o"                  // inttypes.h:73:1:
	PRIoLEAST16                      = "o"                  // inttypes.h:69:1:
	PRIoLEAST32                      = "o"                  // inttypes.h:70:1:
	PRIoLEAST8                       = "o"                  // inttypes.h:68:1:
	PRIu16                           = "u"                  // inttypes.h:79:1:
	PRIu32                           = "u"                  // inttypes.h:80:1:
	PRIu8                            = "u"                  // inttypes.h:78:1:
	PRIuFAST16                       = "u"                  // inttypes.h:89:1:
	PRIuFAST32                       = "u"                  // inttypes.h:90:1:
	PRIuFAST8                        = "u"                  // inttypes.h:88:1:
	PRIuLEAST16                      = "u"                  // inttypes.h:84:1:
	PRIuLEAST32                      = "u"                  // inttypes.h:85:1:
	PRIuLEAST8                       = "u"                  // inttypes.h:83:1:
	PRIx16                           = "x"                  // inttypes.h:94:1:
	PRIx32                           = "x"                  // inttypes.h:95:1:
	PRIx8                            = "x"                  // inttypes.h:93:1:
	PRIxFAST16                       = "x"                  // inttypes.h:104:1:
	PRIxFAST32                       = "x"                  // inttypes.h:105:1:
	PRIxFAST8                        = "x"                  // inttypes.h:103:1:
	PRIxLEAST16                      = "x"                  // inttypes.h:99:1:
	PRIxLEAST32                      = "x"                  // inttypes.h:100:1:
	PRIxLEAST8                       = "x"                  // inttypes.h:98:1:
	PTRDIFF_MAX                      = 9223372036854775807  // stdint.h:19:1:
	PTRDIFF_MIN                      = -9223372036854775808 // stdint.h:18:1:
	SCM_CREDENTIALS                  = 0x02                 // socket.h:365:1:
	SCM_RIGHTS                       = 0x01                 // socket.h:364:1:
	SCM_TIMESTAMP                    = 29                   // socket.h:260:1:
	SCM_TIMESTAMPING                 = 37                   // socket.h:264:1:
	SCM_TIMESTAMPING_OPT_STATS       = 54                   // socket.h:281:1:
	SCM_TIMESTAMPING_PKTINFO         = 58                   // socket.h:285:1:
	SCM_TIMESTAMPNS                  = 35                   // socket.h:262:1:
	SCM_TXTIME                       = 61                   // socket.h:289:1:
	SCM_WIFI_STATUS                  = 41                   // socket.h:267:1:
	SCNd16                           = "hd"                 // inttypes.h:138:1:
	SCNd32                           = "d"                  // inttypes.h:139:1:
	SCNd8                            = "hhd"                // inttypes.h:137:1:
	SCNdFAST16                       = "d"                  // inttypes.h:148:1:
	SCNdFAST32                       = "d"                  // inttypes.h:149:1:
	SCNdFAST8                        = "hhd"                // inttypes.h:147:1:
	SCNdLEAST16                      = "hd"                 // inttypes.h:143:1:
	SCNdLEAST32                      = "d"                  // inttypes.h:144:1:
	SCNdLEAST8                       = "hhd"                // inttypes.h:142:1:
	SCNi16                           = "hi"                 // inttypes.h:153:1:
	SCNi32                           = "i"                  // inttypes.h:154:1:
	SCNi8                            = "hhi"                // inttypes.h:152:1:
	SCNiFAST16                       = "i"                  // inttypes.h:163:1:
	SCNiFAST32                       = "i"                  // inttypes.h:164:1:
	SCNiFAST8                        = "hhi"                // inttypes.h:162:1:
	SCNiLEAST16                      = "hi"                 // inttypes.h:158:1:
	SCNiLEAST32                      = "i"                  // inttypes.h:159:1:
	SCNiLEAST8                       = "hhi"                // inttypes.h:157:1:
	SCNo16                           = "ho"                 // inttypes.h:183:1:
	SCNo32                           = "o"                  // inttypes.h:184:1:
	SCNo8                            = "hho"                // inttypes.h:182:1:
	SCNoFAST16                       = "o"                  // inttypes.h:193:1:
	SCNoFAST32                       = "o"                  // inttypes.h:194:1:
	SCNoFAST8                        = "hho"                // inttypes.h:192:1:
	SCNoLEAST16                      = "ho"                 // inttypes.h:188:1:
	SCNoLEAST32                      = "o"                  // inttypes.h:189:1:
	SCNoLEAST8                       = "hho"                // inttypes.h:187:1:
	SCNu16                           = "hu"                 // inttypes.h:168:1:
	SCNu32                           = "u"                  // inttypes.h:169:1:
	SCNu8                            = "hhu"                // inttypes.h:167:1:
	SCNuFAST16                       = "u"                  // inttypes.h:178:1:
	SCNuFAST32                       = "u"                  // inttypes.h:179:1:
	SCNuFAST8                        = "hhu"                // inttypes.h:177:1:
	SCNuLEAST16                      = "hu"                 // inttypes.h:173:1:
	SCNuLEAST32                      = "u"                  // inttypes.h:174:1:
	SCNuLEAST8                       = "hhu"                // inttypes.h:172:1:
	SCNx16                           = "hx"                 // inttypes.h:198:1:
	SCNx32                           = "x"                  // inttypes.h:199:1:
	SCNx8                            = "hhx"                // inttypes.h:197:1:
	SCNxFAST16                       = "x"                  // inttypes.h:208:1:
	SCNxFAST32                       = "x"                  // inttypes.h:209:1:
	SCNxFAST8                        = "hhx"                // inttypes.h:207:1:
	SCNxLEAST16                      = "hx"                 // inttypes.h:203:1:
	SCNxLEAST32                      = "x"                  // inttypes.h:204:1:
	SCNxLEAST8                       = "hhx"                // inttypes.h:202:1:
	SHUT_RD                          = 0                    // socket.h:79:1:
	SHUT_RDWR                        = 2                    // socket.h:81:1:
	SHUT_WR                          = 1                    // socket.h:80:1:
	SIG_ATOMIC_MAX                   = 2147483647           // stdint.h:93:1:
	SIG_ATOMIC_MIN                   = -2147483648          // stdint.h:92:1:
	SIZE_MAX                         = 18446744073709551615 // stdint.h:20:1:
	SOCK_CLOEXEC                     = 02000000             // socket.h:95:1:
	SOCK_DCCP                        = 6                    // socket.h:91:1:
	SOCK_DGRAM                       = 2                    // socket.h:85:1:
	SOCK_NONBLOCK                    = 04000                // socket.h:96:1:
	SOCK_PACKET                      = 10                   // socket.h:92:1:
	SOCK_RAW                         = 3                    // socket.h:88:1:
	SOCK_RDM                         = 4                    // socket.h:89:1:
	SOCK_SEQPACKET                   = 5                    // socket.h:90:1:
	SOCK_STREAM                      = 1                    // socket.h:84:1:
	SOL_AAL                          = 265                  // socket.h:306:1:
	SOL_ALG                          = 279                  // socket.h:320:1:
	SOL_ATM                          = 264                  // socket.h:305:1:
	SOL_BLUETOOTH                    = 274                  // socket.h:315:1:
	SOL_CAIF                         = 278                  // socket.h:319:1:
	SOL_DCCP                         = 269                  // socket.h:310:1:
	SOL_DECNET                       = 261                  // socket.h:302:1:
	SOL_ICMPV6                       = 58                   // socket.h:299:1:
	SOL_IP                           = 0                    // socket.h:297:1:
	SOL_IPV6                         = 41                   // socket.h:298:1:
	SOL_IRDA                         = 266                  // socket.h:307:1:
	SOL_IUCV                         = 277                  // socket.h:318:1:
	SOL_KCM                          = 281                  // socket.h:322:1:
	SOL_LLC                          = 268                  // socket.h:309:1:
	SOL_NETBEUI                      = 267                  // socket.h:308:1:
	SOL_NETLINK                      = 270                  // socket.h:311:1:
	SOL_NFC                          = 280                  // socket.h:321:1:
	SOL_PACKET                       = 263                  // socket.h:304:1:
	SOL_PNPIPE                       = 275                  // socket.h:316:1:
	SOL_PPPOL2TP                     = 273                  // socket.h:314:1:
	SOL_RAW                          = 255                  // socket.h:301:1:
	SOL_RDS                          = 276                  // socket.h:317:1:
	SOL_RXRPC                        = 272                  // socket.h:313:1:
	SOL_SOCKET                       = 1                    // socket.h:294:1:
	SOL_TIPC                         = 271                  // socket.h:312:1:
	SOL_TLS                          = 282                  // socket.h:323:1:
	SOL_X25                          = 262                  // socket.h:303:1:
	SOL_XDP                          = 283                  // socket.h:324:1:
	SOMAXCONN                        = 128                  // socket.h:326:1:
	SO_ACCEPTCONN                    = 30                   // socket.h:219:1:
	SO_ATTACH_BPF                    = 50                   // socket.h:276:1:
	SO_ATTACH_FILTER                 = 26                   // socket.h:255:1:
	SO_ATTACH_REUSEPORT_CBPF         = 51                   // socket.h:278:1:
	SO_ATTACH_REUSEPORT_EBPF         = 52                   // socket.h:279:1:
	SO_BINDTODEVICE                  = 25                   // socket.h:253:1:
	SO_BINDTOIFINDEX                 = 62                   // socket.h:290:1:
	SO_BPF_EXTENSIONS                = 48                   // socket.h:274:1:
	SO_BROADCAST                     = 6                    // socket.h:205:1:
	SO_BSDCOMPAT                     = 14                   // socket.h:213:1:
	SO_BUSY_POLL                     = 46                   // socket.h:272:1:
	SO_CNX_ADVICE                    = 53                   // socket.h:280:1:
	SO_COOKIE                        = 57                   // socket.h:284:1:
	SO_DEBUG                         = 1                    // socket.h:200:1:
	SO_DETACH_BPF                    = 27                   // socket.h:277:1:
	SO_DETACH_FILTER                 = 27                   // socket.h:256:1:
	SO_DETACH_REUSEPORT_BPF          = 68                   // socket.h:291:1:
	SO_DOMAIN                        = 39                   // socket.h:224:1:
	SO_DONTROUTE                     = 5                    // socket.h:204:1:
	SO_ERROR                         = 4                    // socket.h:203:1:
	SO_GET_FILTER                    = 26                   // socket.h:257:1:
	SO_INCOMING_CPU                  = 49                   // socket.h:275:1:
	SO_INCOMING_NAPI_ID              = 56                   // socket.h:283:1:
	SO_KEEPALIVE                     = 9                    // socket.h:208:1:
	SO_LINGER                        = 13                   // socket.h:212:1:
	SO_LOCK_FILTER                   = 44                   // socket.h:270:1:
	SO_MARK                          = 36                   // socket.h:263:1:
	SO_MAX_PACING_RATE               = 47                   // socket.h:273:1:
	SO_MEMINFO                       = 55                   // socket.h:282:1:
	SO_NOFCS                         = 43                   // socket.h:269:1:
	SO_NO_CHECK                      = 11                   // socket.h:210:1:
	SO_OOBINLINE                     = 10                   // socket.h:209:1:
	SO_PASSCRED                      = 16                   // socket.h:215:1:
	SO_PASSSEC                       = 34                   // socket.h:261:1:
	SO_PEEK_OFF                      = 42                   // socket.h:268:1:
	SO_PEERCRED                      = 17                   // socket.h:216:1:
	SO_PEERGROUPS                    = 59                   // socket.h:286:1:
	SO_PEERNAME                      = 28                   // socket.h:259:1:
	SO_PEERSEC                       = 31                   // socket.h:220:1:
	SO_PRIORITY                      = 12                   // socket.h:211:1:
	SO_PROTOCOL                      = 38                   // socket.h:223:1:
	SO_RCVBUF                        = 8                    // socket.h:207:1:
	SO_RCVBUFFORCE                   = 33                   // socket.h:222:1:
	SO_RCVLOWAT                      = 18                   // socket.h:217:1:
	SO_RCVTIMEO                      = 20                   // socket.h:232:1:
	SO_REUSEADDR                     = 2                    // socket.h:201:1:
	SO_REUSEPORT                     = 15                   // socket.h:214:1:
	SO_RXQ_OVFL                      = 40                   // socket.h:265:1:
	SO_SECURITY_AUTHENTICATION       = 22                   // socket.h:249:1:
	SO_SECURITY_ENCRYPTION_NETWORK   = 24                   // socket.h:251:1:
	SO_SECURITY_ENCRYPTION_TRANSPORT = 23                   // socket.h:250:1:
	SO_SELECT_ERR_QUEUE              = 45                   // socket.h:271:1:
	SO_SNDBUF                        = 7                    // socket.h:206:1:
	SO_SNDBUFFORCE                   = 32                   // socket.h:221:1:
	SO_SNDLOWAT                      = 19                   // socket.h:218:1:
	SO_SNDTIMEO                      = 21                   // socket.h:233:1:
	SO_TIMESTAMP                     = 29                   // socket.h:243:1:
	SO_TIMESTAMPING                  = 37                   // socket.h:245:1:
	SO_TIMESTAMPNS                   = 35                   // socket.h:244:1:
	SO_TXTIME                        = 61                   // socket.h:288:1:
	SO_TYPE                          = 3                    // socket.h:202:1:
	SO_WIFI_STATUS                   = 41                   // socket.h:266:1:
	SO_ZEROCOPY                      = 60                   // socket.h:287:1:
	TRY_AGAIN                        = 2                    // netdb.h:124:1:
	UINT16_MAX                       = 65535                // stdint.h:49:1:
	UINT32_MAX                       = 4294967295           // stdint.h:50:1:
	UINT64_MAX                       = 18446744073709551615 // stdint.h:51:1:
	UINT8_MAX                        = 255                  // stdint.h:48:1:
	UINTMAX_MAX                      = 18446744073709551615 // stdint.h:79:1:
	UINTPTR_MAX                      = 18446744073709551615 // stdint.h:17:1:
	UINT_FAST16_MAX                  = 4294967295           // stdint.h:12:1:
	UINT_FAST32_MAX                  = 4294967295           // stdint.h:13:1:
	UINT_FAST64_MAX                  = 18446744073709551615 // stdint.h:70:1:
	UINT_FAST8_MAX                   = 255                  // stdint.h:69:1:
	UINT_LEAST16_MAX                 = 65535                // stdint.h:73:1:
	UINT_LEAST32_MAX                 = 4294967295           // stdint.h:74:1:
	UINT_LEAST64_MAX                 = 18446744073709551615 // stdint.h:75:1:
	UINT_LEAST8_MAX                  = 255                  // stdint.h:72:1:
	WCHAR_MAX                        = 2147483647           // stdint.h:88:1:
	WCHAR_MIN                        = -2147483648          // stdint.h:89:1:
	WINT_MAX                         = 4294967295           // stdint.h:82:1:
	WINT_MIN                         = 0                    // stdint.h:81:1:
	X_BSD_SOURCE                     = 1                    // features.h:15:1:
	X_FEATURES_H                     = 0                    // features.h:2:1:
	X_FILE_OFFSET_BITS               = 64                   // <builtin>:25:1:
	X_INTTYPES_H                     = 0                    // inttypes.h:2:1:
	X_LP64                           = 1                    // <predefined>:312:1:
	X_NETDB_H                        = 0                    // netdb.h:2:1:
	X_NETINET_IN_H                   = 0                    // in.h:2:1:
	X_STDC_PREDEF_H                  = 1                    // <predefined>:174:1:
	X_STDINT_H                       = 0                    // stdint.h:2:1:
	X_SYS_SOCKET_H                   = 0                    // socket.h:2:1:
	X_XOPEN_SOURCE                   = 700                  // features.h:16:1:
	Linux                            = 1                    // <predefined>:255:1:
	Unix                             = 1                    // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Uintptr_t = uint64 /* alltypes.h:55:24 */

type Intptr_t = int64 /* alltypes.h:70:15 */

type Int8_t = int8 /* alltypes.h:96:25 */

type Int16_t = int16 /* alltypes.h:101:25 */

type Int32_t = int32 /* alltypes.h:106:25 */

type Int64_t = int64 /* alltypes.h:111:25 */

type Intmax_t = int64 /* alltypes.h:116:25 */

type Uint8_t = uint8 /* alltypes.h:121:25 */

type Uint16_t = uint16 /* alltypes.h:126:25 */

type Uint32_t = uint32 /* alltypes.h:131:25 */

type Uint64_t = uint64 /* alltypes.h:136:25 */

type Uintmax_t = uint64 /* alltypes.h:146:25 */

type Int_fast8_t = Int8_t   /* stdint.h:22:16 */
type Int_fast64_t = Int64_t /* stdint.h:23:17 */

type Int_least8_t = Int8_t   /* stdint.h:25:17 */
type Int_least16_t = Int16_t /* stdint.h:26:17 */
type Int_least32_t = Int32_t /* stdint.h:27:17 */
type Int_least64_t = Int64_t /* stdint.h:28:17 */

type Uint_fast8_t = Uint8_t   /* stdint.h:30:17 */
type Uint_fast64_t = Uint64_t /* stdint.h:31:18 */

type Uint_least8_t = Uint8_t   /* stdint.h:33:18 */
type Uint_least16_t = Uint16_t /* stdint.h:34:18 */
type Uint_least32_t = Uint32_t /* stdint.h:35:18 */
type Uint_least64_t = Uint64_t /* stdint.h:36:18 */

type Int_fast16_t = Int32_t   /* stdint.h:1:17 */
type Int_fast32_t = Int32_t   /* stdint.h:2:17 */
type Uint_fast16_t = Uint32_t /* stdint.h:3:18 */
type Uint_fast32_t = Uint32_t /* stdint.h:4:18 */

type Imaxdiv_t = struct {
	Fquot Intmax_t
	Frem  Intmax_t
} /* inttypes.h:14:40 */

type Ssize_t = int64 /* alltypes.h:65:15 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Uid_t = uint32 /* alltypes.h:245:18 */

type Gid_t = uint32 /* alltypes.h:250:18 */

type Iovec = struct {
	Fiov_base uintptr
	Fiov_len  Size_t
} /* alltypes.h:355:1 */

type Socklen_t = uint32 /* alltypes.h:361:18 */

type Sa_family_t = uint16 /* alltypes.h:366:24 */

type Msghdr = struct {
	Fmsg_name       uintptr
	Fmsg_namelen    Socklen_t
	F__ccgo_pad1    [4]byte
	Fmsg_iov        uintptr
	Fmsg_iovlen     int32
	F__pad1         int32
	Fmsg_control    uintptr
	Fmsg_controllen Socklen_t
	F__pad2         int32
	Fmsg_flags      int32
	F__ccgo_pad2    [4]byte
} /* socket.h:22:1 */

type Cmsghdr = struct {
	Fcmsg_len   Socklen_t
	F__pad1     int32
	Fcmsg_level int32
	Fcmsg_type  int32
} /* socket.h:44:1 */

type Linger = struct {
	Fl_onoff  int32
	Fl_linger int32
} /* socket.h:74:1 */

type Sockaddr = struct {
	Fsa_family Sa_family_t
	Fsa_data   [14]int8
} /* socket.h:367:1 */

type Sockaddr_storage = struct {
	Fss_family    Sa_family_t
	F__ss_padding [118]int8
	F__ss_align   uint64
} /* socket.h:372:1 */

type In_port_t = Uint16_t                  /* in.h:12:18 */
type In_addr_t = Uint32_t                  /* in.h:13:18 */
type In_addr = struct{ Fs_addr In_addr_t } /* in.h:14:1 */

type Sockaddr_in = struct {
	Fsin_family Sa_family_t
	Fsin_port   In_port_t
	Fsin_addr   struct{ Fs_addr In_addr_t }
	Fsin_zero   [8]Uint8_t
} /* in.h:16:1 */

type In6_addr = struct {
	F__in6_union struct {
		F__ccgo_pad1 [0]uint32
		F__s6_addr   [16]Uint8_t
	}
} /* in.h:23:1 */

type Sockaddr_in6 = struct {
	Fsin6_family   Sa_family_t
	Fsin6_port     In_port_t
	Fsin6_flowinfo Uint32_t
	Fsin6_addr     struct {
		F__in6_union struct {
			F__ccgo_pad1 [0]uint32
			F__s6_addr   [16]Uint8_t
		}
	}
	Fsin6_scope_id Uint32_t
} /* in.h:34:1 */

type Ipv6_mreq = struct {
	Fipv6mr_multiaddr struct {
		F__in6_union struct {
			F__ccgo_pad1 [0]uint32
			F__s6_addr   [16]Uint8_t
		}
	}
	Fipv6mr_interface uint32
} /* in.h:42:1 */

type Ip_opts = struct {
	Fip_dst  struct{ Fs_addr In_addr_t }
	Fip_opts [40]int8
} /* in.h:229:1 */

type Ip_mreq = struct {
	Fimr_multiaddr struct{ Fs_addr In_addr_t }
	Fimr_interface struct{ Fs_addr In_addr_t }
} /* in.h:247:1 */

type Ip_mreqn = struct {
	Fimr_multiaddr struct{ Fs_addr In_addr_t }
	Fimr_address   struct{ Fs_addr In_addr_t }
	Fimr_ifindex   int32
} /* in.h:252:1 */

type Ip_mreq_source = struct {
	Fimr_multiaddr  struct{ Fs_addr In_addr_t }
	Fimr_interface  struct{ Fs_addr In_addr_t }
	Fimr_sourceaddr struct{ Fs_addr In_addr_t }
} /* in.h:258:1 */

type Ip_msfilter = struct {
	Fimsf_multiaddr struct{ Fs_addr In_addr_t }
	Fimsf_interface struct{ Fs_addr In_addr_t }
	Fimsf_fmode     Uint32_t
	Fimsf_numsrc    Uint32_t
	Fimsf_slist     [1]struct{ Fs_addr In_addr_t }
} /* in.h:264:1 */

type Group_req = struct {
	Fgr_interface Uint32_t
	F__ccgo_pad1  [4]byte
	Fgr_group     struct {
		Fss_family    Sa_family_t
		F__ss_padding [118]int8
		F__ss_align   uint64
	}
} /* in.h:275:1 */

type Group_source_req = struct {
	Fgsr_interface Uint32_t
	F__ccgo_pad1   [4]byte
	Fgsr_group     struct {
		Fss_family    Sa_family_t
		F__ss_padding [118]int8
		F__ss_align   uint64
	}
	Fgsr_source struct {
		Fss_family    Sa_family_t
		F__ss_padding [118]int8
		F__ss_align   uint64
	}
} /* in.h:280:1 */

type Group_filter = struct {
	Fgf_interface Uint32_t
	F__ccgo_pad1  [4]byte
	Fgf_group     struct {
		Fss_family    Sa_family_t
		F__ss_padding [118]int8
		F__ss_align   uint64
	}
	Fgf_fmode  Uint32_t
	Fgf_numsrc Uint32_t
	Fgf_slist  [1]struct {
		Fss_family    Sa_family_t
		F__ss_padding [118]int8
		F__ss_align   uint64
	}
} /* in.h:286:1 */

type In_pktinfo = struct {
	Fipi_ifindex  int32
	Fipi_spec_dst struct{ Fs_addr In_addr_t }
	Fipi_addr     struct{ Fs_addr In_addr_t }
} /* in.h:297:1 */

type In6_pktinfo = struct {
	Fipi6_addr struct {
		F__in6_union struct {
			F__ccgo_pad1 [0]uint32
			F__s6_addr   [16]Uint8_t
		}
	}
	Fipi6_ifindex uint32
} /* in.h:303:1 */

type Ip6_mtuinfo = struct {
	Fip6m_addr struct {
		Fsin6_family   Sa_family_t
		Fsin6_port     In_port_t
		Fsin6_flowinfo Uint32_t
		Fsin6_addr     struct {
			F__in6_union struct {
				F__ccgo_pad1 [0]uint32
				F__s6_addr   [16]Uint8_t
			}
		}
		Fsin6_scope_id Uint32_t
	}
	Fip6m_mtu Uint32_t
} /* in.h:308:1 */

type Addrinfo = struct {
	Fai_flags     int32
	Fai_family    int32
	Fai_socktype  int32
	Fai_protocol  int32
	Fai_addrlen   Socklen_t
	F__ccgo_pad1  [4]byte
	Fai_addr      uintptr
	Fai_canonname uintptr
	Fai_next      uintptr
} /* netdb.h:16:1 */

// Legacy functions follow (marked OBsolete in SUS)

type Netent = struct {
	Fn_name     uintptr
	Fn_aliases  uintptr
	Fn_addrtype int32
	Fn_net      Uint32_t
} /* netdb.h:62:1 */

type Hostent = struct {
	Fh_name      uintptr
	Fh_aliases   uintptr
	Fh_addrtype  int32
	Fh_length    int32
	Fh_addr_list uintptr
} /* netdb.h:69:1 */

type Servent = struct {
	Fs_name      uintptr
	Fs_aliases   uintptr
	Fs_port      int32
	F__ccgo_pad1 [4]byte
	Fs_proto     uintptr
} /* netdb.h:78:1 */

type Protoent = struct {
	Fp_name      uintptr
	Fp_aliases   uintptr
	Fp_proto     int32
	F__ccgo_pad1 [4]byte
} /* netdb.h:85:1 */

var _ int8 /* gen.c:2:13: */
