// Code generated by 'ccgo sys/socket/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o sys/socket/socket_linux_amd64.go -pkgname socket -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package socket

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	AF_ALG                           = 38         // socket.h:190:1:
	AF_APPLETALK                     = 5          // socket.h:156:1:
	AF_ASH                           = 18         // socket.h:170:1:
	AF_ATMPVC                        = 8          // socket.h:159:1:
	AF_ATMSVC                        = 20         // socket.h:172:1:
	AF_AX25                          = 3          // socket.h:154:1:
	AF_BLUETOOTH                     = 31         // socket.h:183:1:
	AF_BRIDGE                        = 7          // socket.h:158:1:
	AF_CAIF                          = 37         // socket.h:189:1:
	AF_CAN                           = 29         // socket.h:181:1:
	AF_DECnet                        = 12         // socket.h:163:1:
	AF_ECONET                        = 19         // socket.h:171:1:
	AF_FILE                          = 1          // socket.h:152:1:
	AF_IB                            = 27         // socket.h:179:1:
	AF_IEEE802154                    = 36         // socket.h:188:1:
	AF_INET                          = 2          // socket.h:153:1:
	AF_INET6                         = 10         // socket.h:161:1:
	AF_IPX                           = 4          // socket.h:155:1:
	AF_IRDA                          = 23         // socket.h:175:1:
	AF_ISDN                          = 34         // socket.h:186:1:
	AF_IUCV                          = 32         // socket.h:184:1:
	AF_KCM                           = 41         // socket.h:193:1:
	AF_KEY                           = 15         // socket.h:166:1:
	AF_LLC                           = 26         // socket.h:178:1:
	AF_LOCAL                         = 1          // socket.h:150:1:
	AF_MAX                           = 45         // socket.h:197:1:
	AF_MPLS                          = 28         // socket.h:180:1:
	AF_NETBEUI                       = 13         // socket.h:164:1:
	AF_NETLINK                       = 16         // socket.h:167:1:
	AF_NETROM                        = 6          // socket.h:157:1:
	AF_NFC                           = 39         // socket.h:191:1:
	AF_PACKET                        = 17         // socket.h:169:1:
	AF_PHONET                        = 35         // socket.h:187:1:
	AF_PPPOX                         = 24         // socket.h:176:1:
	AF_QIPCRTR                       = 42         // socket.h:194:1:
	AF_RDS                           = 21         // socket.h:173:1:
	AF_ROSE                          = 11         // socket.h:162:1:
	AF_ROUTE                         = 16         // socket.h:168:1:
	AF_RXRPC                         = 33         // socket.h:185:1:
	AF_SECURITY                      = 14         // socket.h:165:1:
	AF_SMC                           = 43         // socket.h:195:1:
	AF_SNA                           = 22         // socket.h:174:1:
	AF_TIPC                          = 30         // socket.h:182:1:
	AF_UNIX                          = 1          // socket.h:151:1:
	AF_UNSPEC                        = 0          // socket.h:149:1:
	AF_VSOCK                         = 40         // socket.h:192:1:
	AF_WANPIPE                       = 25         // socket.h:177:1:
	AF_X25                           = 9          // socket.h:160:1:
	AF_XDP                           = 44         // socket.h:196:1:
	FEATURES_H                       = 0          // features.h:2:1:
	MSG_BATCH                        = 0x40000    // socket.h:345:1:
	MSG_CMSG_CLOEXEC                 = 0x40000000 // socket.h:348:1:
	MSG_CONFIRM                      = 0x0800     // socket.h:339:1:
	MSG_CTRUNC                       = 0x0008     // socket.h:331:1:
	MSG_DONTROUTE                    = 0x0004     // socket.h:330:1:
	MSG_DONTWAIT                     = 0x0040     // socket.h:334:1:
	MSG_EOR                          = 0x0080     // socket.h:335:1:
	MSG_ERRQUEUE                     = 0x2000     // socket.h:341:1:
	MSG_FASTOPEN                     = 0x20000000 // socket.h:347:1:
	MSG_FIN                          = 0x0200     // socket.h:337:1:
	MSG_MORE                         = 0x8000     // socket.h:343:1:
	MSG_NOSIGNAL                     = 0x4000     // socket.h:342:1:
	MSG_OOB                          = 0x0001     // socket.h:328:1:
	MSG_PEEK                         = 0x0002     // socket.h:329:1:
	MSG_PROXY                        = 0x0010     // socket.h:332:1:
	MSG_RST                          = 0x1000     // socket.h:340:1:
	MSG_SYN                          = 0x0400     // socket.h:338:1:
	MSG_TRUNC                        = 0x0020     // socket.h:333:1:
	MSG_WAITALL                      = 0x0100     // socket.h:336:1:
	MSG_WAITFORONE                   = 0x10000    // socket.h:344:1:
	MSG_ZEROCOPY                     = 0x4000000  // socket.h:346:1:
	PF_ALG                           = 38         // socket.h:140:1:
	PF_APPLETALK                     = 5          // socket.h:106:1:
	PF_ASH                           = 18         // socket.h:120:1:
	PF_ATMPVC                        = 8          // socket.h:109:1:
	PF_ATMSVC                        = 20         // socket.h:122:1:
	PF_AX25                          = 3          // socket.h:104:1:
	PF_BLUETOOTH                     = 31         // socket.h:133:1:
	PF_BRIDGE                        = 7          // socket.h:108:1:
	PF_CAIF                          = 37         // socket.h:139:1:
	PF_CAN                           = 29         // socket.h:131:1:
	PF_DECnet                        = 12         // socket.h:113:1:
	PF_ECONET                        = 19         // socket.h:121:1:
	PF_FILE                          = 1          // socket.h:102:1:
	PF_IB                            = 27         // socket.h:129:1:
	PF_IEEE802154                    = 36         // socket.h:138:1:
	PF_INET                          = 2          // socket.h:103:1:
	PF_INET6                         = 10         // socket.h:111:1:
	PF_IPX                           = 4          // socket.h:105:1:
	PF_IRDA                          = 23         // socket.h:125:1:
	PF_ISDN                          = 34         // socket.h:136:1:
	PF_IUCV                          = 32         // socket.h:134:1:
	PF_KCM                           = 41         // socket.h:143:1:
	PF_KEY                           = 15         // socket.h:116:1:
	PF_LLC                           = 26         // socket.h:128:1:
	PF_LOCAL                         = 1          // socket.h:100:1:
	PF_MAX                           = 45         // socket.h:147:1:
	PF_MPLS                          = 28         // socket.h:130:1:
	PF_NETBEUI                       = 13         // socket.h:114:1:
	PF_NETLINK                       = 16         // socket.h:117:1:
	PF_NETROM                        = 6          // socket.h:107:1:
	PF_NFC                           = 39         // socket.h:141:1:
	PF_PACKET                        = 17         // socket.h:119:1:
	PF_PHONET                        = 35         // socket.h:137:1:
	PF_PPPOX                         = 24         // socket.h:126:1:
	PF_QIPCRTR                       = 42         // socket.h:144:1:
	PF_RDS                           = 21         // socket.h:123:1:
	PF_ROSE                          = 11         // socket.h:112:1:
	PF_ROUTE                         = 16         // socket.h:118:1:
	PF_RXRPC                         = 33         // socket.h:135:1:
	PF_SECURITY                      = 14         // socket.h:115:1:
	PF_SMC                           = 43         // socket.h:145:1:
	PF_SNA                           = 22         // socket.h:124:1:
	PF_TIPC                          = 30         // socket.h:132:1:
	PF_UNIX                          = 1          // socket.h:101:1:
	PF_UNSPEC                        = 0          // socket.h:99:1:
	PF_VSOCK                         = 40         // socket.h:142:1:
	PF_WANPIPE                       = 25         // socket.h:127:1:
	PF_X25                           = 9          // socket.h:110:1:
	PF_XDP                           = 44         // socket.h:146:1:
	SCM_CREDENTIALS                  = 0x02       // socket.h:365:1:
	SCM_RIGHTS                       = 0x01       // socket.h:364:1:
	SCM_TIMESTAMP                    = 29         // socket.h:260:1:
	SCM_TIMESTAMPING                 = 37         // socket.h:264:1:
	SCM_TIMESTAMPING_OPT_STATS       = 54         // socket.h:281:1:
	SCM_TIMESTAMPING_PKTINFO         = 58         // socket.h:285:1:
	SCM_TIMESTAMPNS                  = 35         // socket.h:262:1:
	SCM_TXTIME                       = 61         // socket.h:289:1:
	SCM_WIFI_STATUS                  = 41         // socket.h:267:1:
	SHUT_RD                          = 0          // socket.h:79:1:
	SHUT_RDWR                        = 2          // socket.h:81:1:
	SHUT_WR                          = 1          // socket.h:80:1:
	SOCK_CLOEXEC                     = 02000000   // socket.h:95:1:
	SOCK_DCCP                        = 6          // socket.h:91:1:
	SOCK_DGRAM                       = 2          // socket.h:85:1:
	SOCK_NONBLOCK                    = 04000      // socket.h:96:1:
	SOCK_PACKET                      = 10         // socket.h:92:1:
	SOCK_RAW                         = 3          // socket.h:88:1:
	SOCK_RDM                         = 4          // socket.h:89:1:
	SOCK_SEQPACKET                   = 5          // socket.h:90:1:
	SOCK_STREAM                      = 1          // socket.h:84:1:
	SOL_AAL                          = 265        // socket.h:306:1:
	SOL_ALG                          = 279        // socket.h:320:1:
	SOL_ATM                          = 264        // socket.h:305:1:
	SOL_BLUETOOTH                    = 274        // socket.h:315:1:
	SOL_CAIF                         = 278        // socket.h:319:1:
	SOL_DCCP                         = 269        // socket.h:310:1:
	SOL_DECNET                       = 261        // socket.h:302:1:
	SOL_ICMPV6                       = 58         // socket.h:299:1:
	SOL_IP                           = 0          // socket.h:297:1:
	SOL_IPV6                         = 41         // socket.h:298:1:
	SOL_IRDA                         = 266        // socket.h:307:1:
	SOL_IUCV                         = 277        // socket.h:318:1:
	SOL_KCM                          = 281        // socket.h:322:1:
	SOL_LLC                          = 268        // socket.h:309:1:
	SOL_NETBEUI                      = 267        // socket.h:308:1:
	SOL_NETLINK                      = 270        // socket.h:311:1:
	SOL_NFC                          = 280        // socket.h:321:1:
	SOL_PACKET                       = 263        // socket.h:304:1:
	SOL_PNPIPE                       = 275        // socket.h:316:1:
	SOL_PPPOL2TP                     = 273        // socket.h:314:1:
	SOL_RAW                          = 255        // socket.h:301:1:
	SOL_RDS                          = 276        // socket.h:317:1:
	SOL_RXRPC                        = 272        // socket.h:313:1:
	SOL_SOCKET                       = 1          // socket.h:294:1:
	SOL_TIPC                         = 271        // socket.h:312:1:
	SOL_TLS                          = 282        // socket.h:323:1:
	SOL_X25                          = 262        // socket.h:303:1:
	SOL_XDP                          = 283        // socket.h:324:1:
	SOMAXCONN                        = 128        // socket.h:326:1:
	SO_ACCEPTCONN                    = 30         // socket.h:219:1:
	SO_ATTACH_BPF                    = 50         // socket.h:276:1:
	SO_ATTACH_FILTER                 = 26         // socket.h:255:1:
	SO_ATTACH_REUSEPORT_CBPF         = 51         // socket.h:278:1:
	SO_ATTACH_REUSEPORT_EBPF         = 52         // socket.h:279:1:
	SO_BINDTODEVICE                  = 25         // socket.h:253:1:
	SO_BINDTOIFINDEX                 = 62         // socket.h:290:1:
	SO_BPF_EXTENSIONS                = 48         // socket.h:274:1:
	SO_BROADCAST                     = 6          // socket.h:205:1:
	SO_BSDCOMPAT                     = 14         // socket.h:213:1:
	SO_BUSY_POLL                     = 46         // socket.h:272:1:
	SO_CNX_ADVICE                    = 53         // socket.h:280:1:
	SO_COOKIE                        = 57         // socket.h:284:1:
	SO_DEBUG                         = 1          // socket.h:200:1:
	SO_DETACH_BPF                    = 27         // socket.h:277:1:
	SO_DETACH_FILTER                 = 27         // socket.h:256:1:
	SO_DETACH_REUSEPORT_BPF          = 68         // socket.h:291:1:
	SO_DOMAIN                        = 39         // socket.h:224:1:
	SO_DONTROUTE                     = 5          // socket.h:204:1:
	SO_ERROR                         = 4          // socket.h:203:1:
	SO_GET_FILTER                    = 26         // socket.h:257:1:
	SO_INCOMING_CPU                  = 49         // socket.h:275:1:
	SO_INCOMING_NAPI_ID              = 56         // socket.h:283:1:
	SO_KEEPALIVE                     = 9          // socket.h:208:1:
	SO_LINGER                        = 13         // socket.h:212:1:
	SO_LOCK_FILTER                   = 44         // socket.h:270:1:
	SO_MARK                          = 36         // socket.h:263:1:
	SO_MAX_PACING_RATE               = 47         // socket.h:273:1:
	SO_MEMINFO                       = 55         // socket.h:282:1:
	SO_NOFCS                         = 43         // socket.h:269:1:
	SO_NO_CHECK                      = 11         // socket.h:210:1:
	SO_OOBINLINE                     = 10         // socket.h:209:1:
	SO_PASSCRED                      = 16         // socket.h:215:1:
	SO_PASSSEC                       = 34         // socket.h:261:1:
	SO_PEEK_OFF                      = 42         // socket.h:268:1:
	SO_PEERCRED                      = 17         // socket.h:216:1:
	SO_PEERGROUPS                    = 59         // socket.h:286:1:
	SO_PEERNAME                      = 28         // socket.h:259:1:
	SO_PEERSEC                       = 31         // socket.h:220:1:
	SO_PRIORITY                      = 12         // socket.h:211:1:
	SO_PROTOCOL                      = 38         // socket.h:223:1:
	SO_RCVBUF                        = 8          // socket.h:207:1:
	SO_RCVBUFFORCE                   = 33         // socket.h:222:1:
	SO_RCVLOWAT                      = 18         // socket.h:217:1:
	SO_RCVTIMEO                      = 20         // socket.h:232:1:
	SO_REUSEADDR                     = 2          // socket.h:201:1:
	SO_REUSEPORT                     = 15         // socket.h:214:1:
	SO_RXQ_OVFL                      = 40         // socket.h:265:1:
	SO_SECURITY_AUTHENTICATION       = 22         // socket.h:249:1:
	SO_SECURITY_ENCRYPTION_NETWORK   = 24         // socket.h:251:1:
	SO_SECURITY_ENCRYPTION_TRANSPORT = 23         // socket.h:250:1:
	SO_SELECT_ERR_QUEUE              = 45         // socket.h:271:1:
	SO_SNDBUF                        = 7          // socket.h:206:1:
	SO_SNDBUFFORCE                   = 32         // socket.h:221:1:
	SO_SNDLOWAT                      = 19         // socket.h:218:1:
	SO_SNDTIMEO                      = 21         // socket.h:233:1:
	SO_TIMESTAMP                     = 29         // socket.h:243:1:
	SO_TIMESTAMPING                  = 37         // socket.h:245:1:
	SO_TIMESTAMPNS                   = 35         // socket.h:244:1:
	SO_TXTIME                        = 61         // socket.h:288:1:
	SO_TYPE                          = 3          // socket.h:202:1:
	SO_WIFI_STATUS                   = 41         // socket.h:266:1:
	SO_ZEROCOPY                      = 60         // socket.h:287:1:
	X_BSD_SOURCE                     = 1          // features.h:15:1:
	X_FEATURES_H                     = 0          // features.h:2:1:
	X_FILE_OFFSET_BITS               = 64         // <builtin>:25:1:
	X_LP64                           = 1          // <predefined>:312:1:
	X_STDC_PREDEF_H                  = 1          // <predefined>:174:1:
	X_SYS_SOCKET_H                   = 0          // socket.h:2:1:
	X_XOPEN_SOURCE                   = 700        // features.h:16:1:
	Linux                            = 1          // <predefined>:255:1:
	Unix                             = 1          // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Ssize_t = int64 /* alltypes.h:65:15 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Uid_t = uint32 /* alltypes.h:245:18 */

type Gid_t = uint32 /* alltypes.h:250:18 */

type Iovec = struct {
	Fiov_base uintptr
	Fiov_len  Size_t
} /* alltypes.h:355:1 */

type Socklen_t = uint32 /* alltypes.h:361:18 */

type Sa_family_t = uint16 /* alltypes.h:366:24 */

type Msghdr = struct {
	Fmsg_name       uintptr
	Fmsg_namelen    Socklen_t
	F__ccgo_pad1    [4]byte
	Fmsg_iov        uintptr
	Fmsg_iovlen     int32
	F__pad1         int32
	Fmsg_control    uintptr
	Fmsg_controllen Socklen_t
	F__pad2         int32
	Fmsg_flags      int32
	F__ccgo_pad2    [4]byte
} /* socket.h:22:1 */

type Cmsghdr = struct {
	Fcmsg_len   Socklen_t
	F__pad1     int32
	Fcmsg_level int32
	Fcmsg_type  int32
} /* socket.h:44:1 */

type Linger = struct {
	Fl_onoff  int32
	Fl_linger int32
} /* socket.h:74:1 */

type Sockaddr = struct {
	Fsa_family Sa_family_t
	Fsa_data   [14]int8
} /* socket.h:367:1 */

type Sockaddr_storage = struct {
	Fss_family    Sa_family_t
	F__ss_padding [118]int8
	F__ss_align   uint64
} /* socket.h:372:1 */

var _ int8 /* gen.c:2:13: */
