// Code generated by 'ccgo unistd/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o unistd/unistd_linux_amd64.go -pkgname unistd -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package unistd

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	FEATURES_H                           = 0      // features.h:2:1:
	F_LOCK                               = 1      // unistd.h:133:1:
	F_OK                                 = 0      // unistd.h:68:1:
	F_TEST                               = 3      // unistd.h:135:1:
	F_TLOCK                              = 2      // unistd.h:134:1:
	F_ULOCK                              = 0      // unistd.h:132:1:
	L_INCR                               = 1      // unistd.h:156:1:
	L_SET                                = 0      // unistd.h:155:1:
	L_XTND                               = 2      // unistd.h:157:1:
	POSIX_CLOSE_RESTART                  = 0      // unistd.h:205:1:
	R_OK                                 = 4      // unistd.h:69:1:
	SEEK_CUR                             = 1      // unistd.h:15:1:
	SEEK_END                             = 2      // unistd.h:16:1:
	SEEK_SET                             = 0      // unistd.h:14:1:
	STDERR_FILENO                        = 2      // unistd.h:12:1:
	STDIN_FILENO                         = 0      // unistd.h:10:1:
	STDOUT_FILENO                        = 1      // unistd.h:11:1:
	UNISTD_H                             = 0      // unistd.h:2:1:
	W_OK                                 = 2      // unistd.h:70:1:
	X_OK                                 = 1      // unistd.h:71:1:
	X_BSD_SOURCE                         = 1      // features.h:15:1:
	X_CS_GNU_LIBC_VERSION                = 2      // unistd.h:425:1:
	X_CS_GNU_LIBPTHREAD_VERSION          = 3      // unistd.h:426:1:
	X_CS_PATH                            = 0      // unistd.h:423:1:
	X_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS  = 4      // unistd.h:427:1:
	X_CS_POSIX_V6_ILP32_OFF32_CFLAGS     = 1116   // unistd.h:430:1:
	X_CS_POSIX_V6_ILP32_OFF32_LDFLAGS    = 1117   // unistd.h:431:1:
	X_CS_POSIX_V6_ILP32_OFF32_LIBS       = 1118   // unistd.h:432:1:
	X_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS  = 1119   // unistd.h:433:1:
	X_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS    = 1120   // unistd.h:434:1:
	X_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS   = 1121   // unistd.h:435:1:
	X_CS_POSIX_V6_ILP32_OFFBIG_LIBS      = 1122   // unistd.h:436:1:
	X_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS = 1123   // unistd.h:437:1:
	X_CS_POSIX_V6_LP64_OFF64_CFLAGS      = 1124   // unistd.h:438:1:
	X_CS_POSIX_V6_LP64_OFF64_LDFLAGS     = 1125   // unistd.h:439:1:
	X_CS_POSIX_V6_LP64_OFF64_LIBS        = 1126   // unistd.h:440:1:
	X_CS_POSIX_V6_LP64_OFF64_LINTFLAGS   = 1127   // unistd.h:441:1:
	X_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS    = 1128   // unistd.h:442:1:
	X_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS   = 1129   // unistd.h:443:1:
	X_CS_POSIX_V6_LPBIG_OFFBIG_LIBS      = 1130   // unistd.h:444:1:
	X_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS = 1131   // unistd.h:445:1:
	X_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS  = 1      // unistd.h:424:1:
	X_CS_POSIX_V7_ILP32_OFF32_CFLAGS     = 1132   // unistd.h:446:1:
	X_CS_POSIX_V7_ILP32_OFF32_LDFLAGS    = 1133   // unistd.h:447:1:
	X_CS_POSIX_V7_ILP32_OFF32_LIBS       = 1134   // unistd.h:448:1:
	X_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS  = 1135   // unistd.h:449:1:
	X_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS    = 1136   // unistd.h:450:1:
	X_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS   = 1137   // unistd.h:451:1:
	X_CS_POSIX_V7_ILP32_OFFBIG_LIBS      = 1138   // unistd.h:452:1:
	X_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS = 1139   // unistd.h:453:1:
	X_CS_POSIX_V7_LP64_OFF64_CFLAGS      = 1140   // unistd.h:454:1:
	X_CS_POSIX_V7_LP64_OFF64_LDFLAGS     = 1141   // unistd.h:455:1:
	X_CS_POSIX_V7_LP64_OFF64_LIBS        = 1142   // unistd.h:456:1:
	X_CS_POSIX_V7_LP64_OFF64_LINTFLAGS   = 1143   // unistd.h:457:1:
	X_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS    = 1144   // unistd.h:458:1:
	X_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS   = 1145   // unistd.h:459:1:
	X_CS_POSIX_V7_LPBIG_OFFBIG_LIBS      = 1146   // unistd.h:460:1:
	X_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS = 1147   // unistd.h:461:1:
	X_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS  = 5      // unistd.h:428:1:
	X_CS_V6_ENV                          = 1148   // unistd.h:462:1:
	X_CS_V7_ENV                          = 1149   // unistd.h:463:1:
	X_FEATURES_H                         = 0      // features.h:2:1:
	X_FILE_OFFSET_BITS                   = 64     // <builtin>:25:1:
	X_LP64                               = 1      // <predefined>:312:1:
	X_PC_2_SYMLINKS                      = 20     // unistd.h:278:1:
	X_PC_ALLOC_SIZE_MIN                  = 18     // unistd.h:276:1:
	X_PC_ASYNC_IO                        = 10     // unistd.h:268:1:
	X_PC_CHOWN_RESTRICTED                = 6      // unistd.h:264:1:
	X_PC_FILESIZEBITS                    = 13     // unistd.h:271:1:
	X_PC_LINK_MAX                        = 0      // unistd.h:258:1:
	X_PC_MAX_CANON                       = 1      // unistd.h:259:1:
	X_PC_MAX_INPUT                       = 2      // unistd.h:260:1:
	X_PC_NAME_MAX                        = 3      // unistd.h:261:1:
	X_PC_NO_TRUNC                        = 7      // unistd.h:265:1:
	X_PC_PATH_MAX                        = 4      // unistd.h:262:1:
	X_PC_PIPE_BUF                        = 5      // unistd.h:263:1:
	X_PC_PRIO_IO                         = 11     // unistd.h:269:1:
	X_PC_REC_INCR_XFER_SIZE              = 14     // unistd.h:272:1:
	X_PC_REC_MAX_XFER_SIZE               = 15     // unistd.h:273:1:
	X_PC_REC_MIN_XFER_SIZE               = 16     // unistd.h:274:1:
	X_PC_REC_XFER_ALIGN                  = 17     // unistd.h:275:1:
	X_PC_SOCK_MAXBUF                     = 12     // unistd.h:270:1:
	X_PC_SYMLINK_MAX                     = 19     // unistd.h:277:1:
	X_PC_SYNC_IO                         = 9      // unistd.h:267:1:
	X_PC_VDISABLE                        = 8      // unistd.h:266:1:
	X_POSIX2_C_BIND                      = 200809 // unistd.h:252:1:
	X_POSIX2_VERSION                     = 200809 // unistd.h:212:1:
	X_POSIX_ADVISORY_INFO                = 200809 // unistd.h:214:1:
	X_POSIX_ASYNCHRONOUS_IO              = 200809 // unistd.h:248:1:
	X_POSIX_BARRIERS                     = 200809 // unistd.h:245:1:
	X_POSIX_CHOWN_RESTRICTED             = 1      // unistd.h:215:1:
	X_POSIX_CLOCK_SELECTION              = 200809 // unistd.h:244:1:
	X_POSIX_CPUTIME                      = 200809 // unistd.h:243:1:
	X_POSIX_FSYNC                        = 200809 // unistd.h:223:1:
	X_POSIX_IPV6                         = 200809 // unistd.h:216:1:
	X_POSIX_JOB_CONTROL                  = 1      // unistd.h:217:1:
	X_POSIX_MAPPED_FILES                 = 200809 // unistd.h:218:1:
	X_POSIX_MEMLOCK                      = 200809 // unistd.h:219:1:
	X_POSIX_MEMLOCK_RANGE                = 200809 // unistd.h:220:1:
	X_POSIX_MEMORY_PROTECTION            = 200809 // unistd.h:221:1:
	X_POSIX_MESSAGE_PASSING              = 200809 // unistd.h:222:1:
	X_POSIX_MONOTONIC_CLOCK              = 200809 // unistd.h:242:1:
	X_POSIX_NO_TRUNC                     = 1      // unistd.h:224:1:
	X_POSIX_RAW_SOCKETS                  = 200809 // unistd.h:225:1:
	X_POSIX_READER_WRITER_LOCKS          = 200809 // unistd.h:247:1:
	X_POSIX_REALTIME_SIGNALS             = 200809 // unistd.h:226:1:
	X_POSIX_REGEXP                       = 1      // unistd.h:227:1:
	X_POSIX_SAVED_IDS                    = 1      // unistd.h:228:1:
	X_POSIX_SEMAPHORES                   = 200809 // unistd.h:249:1:
	X_POSIX_SHARED_MEMORY_OBJECTS        = 200809 // unistd.h:250:1:
	X_POSIX_SHELL                        = 1      // unistd.h:229:1:
	X_POSIX_SPAWN                        = 200809 // unistd.h:230:1:
	X_POSIX_SPIN_LOCKS                   = 200809 // unistd.h:246:1:
	X_POSIX_THREADS                      = 200809 // unistd.h:233:1:
	X_POSIX_THREAD_ATTR_STACKADDR        = 200809 // unistd.h:236:1:
	X_POSIX_THREAD_ATTR_STACKSIZE        = 200809 // unistd.h:237:1:
	X_POSIX_THREAD_CPUTIME               = 200809 // unistd.h:239:1:
	X_POSIX_THREAD_PRIORITY_SCHEDULING   = 200809 // unistd.h:238:1:
	X_POSIX_THREAD_PROCESS_SHARED        = 200809 // unistd.h:234:1:
	X_POSIX_THREAD_SAFE_FUNCTIONS        = 200809 // unistd.h:235:1:
	X_POSIX_TIMEOUTS                     = 200809 // unistd.h:241:1:
	X_POSIX_TIMERS                       = 200809 // unistd.h:240:1:
	X_POSIX_V6_LP64_OFF64                = 1      // posix.h:1:1:
	X_POSIX_V7_LP64_OFF64                = 1      // posix.h:2:1:
	X_POSIX_VDISABLE                     = 0      // unistd.h:231:1:
	X_POSIX_VERSION                      = 200809 // unistd.h:211:1:
	X_SC_2_CHAR_TERM                     = 95     // unistd.h:362:1:
	X_SC_2_C_BIND                        = 47     // unistd.h:326:1:
	X_SC_2_C_DEV                         = 48     // unistd.h:327:1:
	X_SC_2_FORT_DEV                      = 49     // unistd.h:328:1:
	X_SC_2_FORT_RUN                      = 50     // unistd.h:329:1:
	X_SC_2_LOCALEDEF                     = 52     // unistd.h:331:1:
	X_SC_2_PBS                           = 168    // unistd.h:390:1:
	X_SC_2_PBS_ACCOUNTING                = 169    // unistd.h:391:1:
	X_SC_2_PBS_CHECKPOINT                = 175    // unistd.h:397:1:
	X_SC_2_PBS_LOCATE                    = 170    // unistd.h:392:1:
	X_SC_2_PBS_MESSAGE                   = 171    // unistd.h:393:1:
	X_SC_2_PBS_TRACK                     = 172    // unistd.h:394:1:
	X_SC_2_SW_DEV                        = 51     // unistd.h:330:1:
	X_SC_2_UPE                           = 97     // unistd.h:363:1:
	X_SC_2_VERSION                       = 46     // unistd.h:325:1:
	X_SC_ADVISORY_INFO                   = 132    // unistd.h:375:1:
	X_SC_AIO_LISTIO_MAX                  = 23     // unistd.h:303:1:
	X_SC_AIO_MAX                         = 24     // unistd.h:304:1:
	X_SC_AIO_PRIO_DELTA_MAX              = 25     // unistd.h:305:1:
	X_SC_ARG_MAX                         = 0      // unistd.h:280:1:
	X_SC_ASYNCHRONOUS_IO                 = 12     // unistd.h:292:1:
	X_SC_ATEXIT_MAX                      = 87     // unistd.h:354:1:
	X_SC_AVPHYS_PAGES                    = 86     // unistd.h:353:1:
	X_SC_BARRIERS                        = 133    // unistd.h:376:1:
	X_SC_BC_BASE_MAX                     = 36     // unistd.h:317:1:
	X_SC_BC_DIM_MAX                      = 37     // unistd.h:318:1:
	X_SC_BC_SCALE_MAX                    = 38     // unistd.h:319:1:
	X_SC_BC_STRING_MAX                   = 39     // unistd.h:320:1:
	X_SC_CHILD_MAX                       = 1      // unistd.h:281:1:
	X_SC_CLK_TCK                         = 2      // unistd.h:282:1:
	X_SC_CLOCK_SELECTION                 = 137    // unistd.h:377:1:
	X_SC_COLL_WEIGHTS_MAX                = 40     // unistd.h:321:1:
	X_SC_CPUTIME                         = 138    // unistd.h:378:1:
	X_SC_DELAYTIMER_MAX                  = 26     // unistd.h:306:1:
	X_SC_EXPR_NEST_MAX                   = 42     // unistd.h:322:1:
	X_SC_FSYNC                           = 15     // unistd.h:295:1:
	X_SC_GETGR_R_SIZE_MAX                = 69     // unistd.h:336:1:
	X_SC_GETPW_R_SIZE_MAX                = 70     // unistd.h:337:1:
	X_SC_HOST_NAME_MAX                   = 180    // unistd.h:402:1:
	X_SC_IOV_MAX                         = 60     // unistd.h:333:1:
	X_SC_IPV6                            = 235    // unistd.h:408:1:
	X_SC_JOB_CONTROL                     = 7      // unistd.h:287:1:
	X_SC_LINE_MAX                        = 43     // unistd.h:323:1:
	X_SC_LOGIN_NAME_MAX                  = 71     // unistd.h:338:1:
	X_SC_MAPPED_FILES                    = 16     // unistd.h:296:1:
	X_SC_MEMLOCK                         = 17     // unistd.h:297:1:
	X_SC_MEMLOCK_RANGE                   = 18     // unistd.h:298:1:
	X_SC_MEMORY_PROTECTION               = 19     // unistd.h:299:1:
	X_SC_MESSAGE_PASSING                 = 20     // unistd.h:300:1:
	X_SC_MONOTONIC_CLOCK                 = 149    // unistd.h:380:1:
	X_SC_MQ_OPEN_MAX                     = 27     // unistd.h:307:1:
	X_SC_MQ_PRIO_MAX                     = 28     // unistd.h:308:1:
	X_SC_NGROUPS_MAX                     = 3      // unistd.h:283:1:
	X_SC_NPROCESSORS_CONF                = 83     // unistd.h:350:1:
	X_SC_NPROCESSORS_ONLN                = 84     // unistd.h:351:1:
	X_SC_NZERO                           = 109    // unistd.h:367:1:
	X_SC_OPEN_MAX                        = 4      // unistd.h:284:1:
	X_SC_PAGESIZE                        = 30     // unistd.h:311:1:
	X_SC_PAGE_SIZE                       = 30     // unistd.h:310:1:
	X_SC_PASS_MAX                        = 88     // unistd.h:355:1:
	X_SC_PHYS_PAGES                      = 85     // unistd.h:352:1:
	X_SC_PRIORITIZED_IO                  = 13     // unistd.h:293:1:
	X_SC_PRIORITY_SCHEDULING             = 10     // unistd.h:290:1:
	X_SC_RAW_SOCKETS                     = 236    // unistd.h:409:1:
	X_SC_READER_WRITER_LOCKS             = 153    // unistd.h:381:1:
	X_SC_REALTIME_SIGNALS                = 9      // unistd.h:289:1:
	X_SC_REGEXP                          = 155    // unistd.h:383:1:
	X_SC_RE_DUP_MAX                      = 44     // unistd.h:324:1:
	X_SC_RTSIG_MAX                       = 31     // unistd.h:312:1:
	X_SC_SAVED_IDS                       = 8      // unistd.h:288:1:
	X_SC_SEMAPHORES                      = 21     // unistd.h:301:1:
	X_SC_SEM_NSEMS_MAX                   = 32     // unistd.h:313:1:
	X_SC_SEM_VALUE_MAX                   = 33     // unistd.h:314:1:
	X_SC_SHARED_MEMORY_OBJECTS           = 22     // unistd.h:302:1:
	X_SC_SHELL                           = 157    // unistd.h:384:1:
	X_SC_SIGQUEUE_MAX                    = 34     // unistd.h:315:1:
	X_SC_SPAWN                           = 159    // unistd.h:385:1:
	X_SC_SPIN_LOCKS                      = 154    // unistd.h:382:1:
	X_SC_SPORADIC_SERVER                 = 160    // unistd.h:386:1:
	X_SC_SS_REPL_MAX                     = 241    // unistd.h:414:1:
	X_SC_STREAMS                         = 174    // unistd.h:396:1:
	X_SC_STREAM_MAX                      = 5      // unistd.h:285:1:
	X_SC_SYMLOOP_MAX                     = 173    // unistd.h:395:1:
	X_SC_SYNCHRONIZED_IO                 = 14     // unistd.h:294:1:
	X_SC_THREADS                         = 67     // unistd.h:334:1:
	X_SC_THREAD_ATTR_STACKADDR           = 77     // unistd.h:344:1:
	X_SC_THREAD_ATTR_STACKSIZE           = 78     // unistd.h:345:1:
	X_SC_THREAD_CPUTIME                  = 139    // unistd.h:379:1:
	X_SC_THREAD_DESTRUCTOR_ITERATIONS    = 73     // unistd.h:340:1:
	X_SC_THREAD_KEYS_MAX                 = 74     // unistd.h:341:1:
	X_SC_THREAD_PRIORITY_SCHEDULING      = 79     // unistd.h:346:1:
	X_SC_THREAD_PRIO_INHERIT             = 80     // unistd.h:347:1:
	X_SC_THREAD_PRIO_PROTECT             = 81     // unistd.h:348:1:
	X_SC_THREAD_PROCESS_SHARED           = 82     // unistd.h:349:1:
	X_SC_THREAD_ROBUST_PRIO_INHERIT      = 247    // unistd.h:420:1:
	X_SC_THREAD_ROBUST_PRIO_PROTECT      = 248    // unistd.h:421:1:
	X_SC_THREAD_SAFE_FUNCTIONS           = 68     // unistd.h:335:1:
	X_SC_THREAD_SPORADIC_SERVER          = 161    // unistd.h:387:1:
	X_SC_THREAD_STACK_MIN                = 75     // unistd.h:342:1:
	X_SC_THREAD_THREADS_MAX              = 76     // unistd.h:343:1:
	X_SC_TIMEOUTS                        = 164    // unistd.h:388:1:
	X_SC_TIMERS                          = 11     // unistd.h:291:1:
	X_SC_TIMER_MAX                       = 35     // unistd.h:316:1:
	X_SC_TRACE                           = 181    // unistd.h:403:1:
	X_SC_TRACE_EVENT_FILTER              = 182    // unistd.h:404:1:
	X_SC_TRACE_EVENT_NAME_MAX            = 242    // unistd.h:415:1:
	X_SC_TRACE_INHERIT                   = 183    // unistd.h:405:1:
	X_SC_TRACE_LOG                       = 184    // unistd.h:406:1:
	X_SC_TRACE_NAME_MAX                  = 243    // unistd.h:416:1:
	X_SC_TRACE_SYS_MAX                   = 244    // unistd.h:417:1:
	X_SC_TRACE_USER_EVENT_MAX            = 245    // unistd.h:418:1:
	X_SC_TTY_NAME_MAX                    = 72     // unistd.h:339:1:
	X_SC_TYPED_MEMORY_OBJECTS            = 165    // unistd.h:389:1:
	X_SC_TZNAME_MAX                      = 6      // unistd.h:286:1:
	X_SC_UIO_MAXIOV                      = 60     // unistd.h:332:1:
	X_SC_V6_ILP32_OFF32                  = 176    // unistd.h:398:1:
	X_SC_V6_ILP32_OFFBIG                 = 177    // unistd.h:399:1:
	X_SC_V6_LP64_OFF64                   = 178    // unistd.h:400:1:
	X_SC_V6_LPBIG_OFFBIG                 = 179    // unistd.h:401:1:
	X_SC_V7_ILP32_OFF32                  = 237    // unistd.h:410:1:
	X_SC_V7_ILP32_OFFBIG                 = 238    // unistd.h:411:1:
	X_SC_V7_LP64_OFF64                   = 239    // unistd.h:412:1:
	X_SC_V7_LPBIG_OFFBIG                 = 240    // unistd.h:413:1:
	X_SC_VERSION                         = 29     // unistd.h:309:1:
	X_SC_XBS5_ILP32_OFF32                = 125    // unistd.h:368:1:
	X_SC_XBS5_ILP32_OFFBIG               = 126    // unistd.h:369:1:
	X_SC_XBS5_LP64_OFF64                 = 127    // unistd.h:370:1:
	X_SC_XBS5_LPBIG_OFFBIG               = 128    // unistd.h:371:1:
	X_SC_XOPEN_CRYPT                     = 92     // unistd.h:359:1:
	X_SC_XOPEN_ENH_I18N                  = 93     // unistd.h:360:1:
	X_SC_XOPEN_LEGACY                    = 129    // unistd.h:372:1:
	X_SC_XOPEN_REALTIME                  = 130    // unistd.h:373:1:
	X_SC_XOPEN_REALTIME_THREADS          = 131    // unistd.h:374:1:
	X_SC_XOPEN_SHM                       = 94     // unistd.h:361:1:
	X_SC_XOPEN_STREAMS                   = 246    // unistd.h:419:1:
	X_SC_XOPEN_UNIX                      = 91     // unistd.h:358:1:
	X_SC_XOPEN_VERSION                   = 89     // unistd.h:356:1:
	X_SC_XOPEN_XCU_VERSION               = 90     // unistd.h:357:1:
	X_SC_XOPEN_XPG2                      = 98     // unistd.h:364:1:
	X_SC_XOPEN_XPG3                      = 99     // unistd.h:365:1:
	X_SC_XOPEN_XPG4                      = 100    // unistd.h:366:1:
	X_STDC_PREDEF_H                      = 1      // <predefined>:174:1:
	X_UNISTD_H                           = 0      // unistd.h:2:1:
	X_XOPEN_ENH_I18N                     = 1      // unistd.h:209:1:
	X_XOPEN_SOURCE                       = 700    // features.h:16:1:
	X_XOPEN_UNIX                         = 1      // unistd.h:208:1:
	X_XOPEN_VERSION                      = 700    // unistd.h:207:1:
	Linux                                = 1      // <predefined>:255:1:
	Unix                                 = 1      // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Ssize_t = int64 /* alltypes.h:65:15 */

type Intptr_t = int64 /* alltypes.h:70:15 */

type Off_t = int64 /* alltypes.h:162:16 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Uid_t = uint32 /* alltypes.h:245:18 */

type Gid_t = uint32 /* alltypes.h:250:18 */

type Useconds_t = uint32 /* alltypes.h:260:18 */

var _ int8 /* gen.c:2:13: */
