// Code generated by 'ccgo langinfo/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o langinfo/langinfo_linux_amd64.go -pkgname langinfo -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package langinfo

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	ABDAY_1            = 0x20000 // langinfo.h:15:1:
	ABDAY_2            = 0x20001 // langinfo.h:16:1:
	ABDAY_3            = 0x20002 // langinfo.h:17:1:
	ABDAY_4            = 0x20003 // langinfo.h:18:1:
	ABDAY_5            = 0x20004 // langinfo.h:19:1:
	ABDAY_6            = 0x20005 // langinfo.h:20:1:
	ABDAY_7            = 0x20006 // langinfo.h:21:1:
	ABMON_1            = 0x2000E // langinfo.h:31:1:
	ABMON_10           = 0x20017 // langinfo.h:40:1:
	ABMON_11           = 0x20018 // langinfo.h:41:1:
	ABMON_12           = 0x20019 // langinfo.h:42:1:
	ABMON_2            = 0x2000F // langinfo.h:32:1:
	ABMON_3            = 0x20010 // langinfo.h:33:1:
	ABMON_4            = 0x20011 // langinfo.h:34:1:
	ABMON_5            = 0x20012 // langinfo.h:35:1:
	ABMON_6            = 0x20013 // langinfo.h:36:1:
	ABMON_7            = 0x20014 // langinfo.h:37:1:
	ABMON_8            = 0x20015 // langinfo.h:38:1:
	ABMON_9            = 0x20016 // langinfo.h:39:1:
	ALT_DIGITS         = 0x2002F // langinfo.h:67:1:
	AM_STR             = 0x20026 // langinfo.h:57:1:
	CODESET            = 14      // langinfo.h:71:1:
	CRNCYSTR           = 0x4000F // langinfo.h:73:1:
	DAY_1              = 0x20007 // langinfo.h:23:1:
	DAY_2              = 0x20008 // langinfo.h:24:1:
	DAY_3              = 0x20009 // langinfo.h:25:1:
	DAY_4              = 0x2000A // langinfo.h:26:1:
	DAY_5              = 0x2000B // langinfo.h:27:1:
	DAY_6              = 0x2000C // langinfo.h:28:1:
	DAY_7              = 0x2000D // langinfo.h:29:1:
	D_FMT              = 0x20029 // langinfo.h:61:1:
	D_T_FMT            = 0x20028 // langinfo.h:60:1:
	ERA                = 0x2002C // langinfo.h:65:1:
	ERA_D_FMT          = 0x2002E // langinfo.h:66:1:
	ERA_D_T_FMT        = 0x20030 // langinfo.h:68:1:
	ERA_T_FMT          = 0x20031 // langinfo.h:69:1:
	FEATURES_H         = 0       // features.h:2:1:
	LANGINFO_H         = 0       // langinfo.h:2:1:
	MON_1              = 0x2001A // langinfo.h:44:1:
	MON_10             = 0x20023 // langinfo.h:53:1:
	MON_11             = 0x20024 // langinfo.h:54:1:
	MON_12             = 0x20025 // langinfo.h:55:1:
	MON_2              = 0x2001B // langinfo.h:45:1:
	MON_3              = 0x2001C // langinfo.h:46:1:
	MON_4              = 0x2001D // langinfo.h:47:1:
	MON_5              = 0x2001E // langinfo.h:48:1:
	MON_6              = 0x2001F // langinfo.h:49:1:
	MON_7              = 0x20020 // langinfo.h:50:1:
	MON_8              = 0x20021 // langinfo.h:51:1:
	MON_9              = 0x20022 // langinfo.h:52:1:
	NL_CAT_LOCALE      = 1       // nl_types.h:9:1:
	NL_SETD            = 1       // nl_types.h:8:1:
	NOEXPR             = 0x50001 // langinfo.h:78:1:
	NOSTR              = 0x50003 // langinfo.h:88:1:
	PM_STR             = 0x20027 // langinfo.h:58:1:
	RADIXCHAR          = 0x10000 // langinfo.h:75:1:
	THOUSEP            = 0x10001 // langinfo.h:76:1:
	T_FMT              = 0x2002A // langinfo.h:62:1:
	T_FMT_AMPM         = 0x2002B // langinfo.h:63:1:
	YESEXPR            = 0x50000 // langinfo.h:77:1:
	YESSTR             = 0x50002 // langinfo.h:87:1:
	X_BSD_SOURCE       = 1       // features.h:15:1:
	X_FEATURES_H       = 0       // features.h:2:1:
	X_FILE_OFFSET_BITS = 64      // <builtin>:25:1:
	X_LANGINFO_H       = 0       // langinfo.h:2:1:
	X_LP64             = 1       // <predefined>:312:1:
	X_NL_TYPES_H       = 0       // nl_types.h:2:1:
	X_STDC_PREDEF_H    = 1       // <predefined>:174:1:
	X_XOPEN_SOURCE     = 700     // features.h:16:1:
	Linux              = 1       // <predefined>:255:1:
	Unix               = 1       // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Nl_item = int32   /* nl_types.h:11:13 */
type Nl_catd = uintptr /* nl_types.h:12:14 */

type Locale_t = uintptr /* alltypes.h:343:32 */

var _ int8 /* gen.c:2:13: */
