// Code generated by 'ccgo time/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o time/time_linux_amd64.go -pkgname time -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package time

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	CLOCKS_PER_SEC           = 1000000 // time.h:63:1:
	CLOCK_BOOTTIME           = 7       // time.h:92:1:
	CLOCK_BOOTTIME_ALARM     = 9       // time.h:94:1:
	CLOCK_MONOTONIC          = 1       // time.h:86:1:
	CLOCK_MONOTONIC_COARSE   = 6       // time.h:91:1:
	CLOCK_MONOTONIC_RAW      = 4       // time.h:89:1:
	CLOCK_PROCESS_CPUTIME_ID = 2       // time.h:87:1:
	CLOCK_REALTIME           = 0       // time.h:85:1:
	CLOCK_REALTIME_ALARM     = 8       // time.h:93:1:
	CLOCK_REALTIME_COARSE    = 5       // time.h:90:1:
	CLOCK_SGI_CYCLE          = 10      // time.h:95:1:
	CLOCK_TAI                = 11      // time.h:96:1:
	CLOCK_THREAD_CPUTIME_ID  = 3       // time.h:88:1:
	FEATURES_H               = 0       // features.h:2:1:
	TIMER_ABSTIME            = 1       // time.h:98:1:
	TIME_H                   = 0       // time.h:2:1:
	TIME_UTC                 = 1       // time.h:65:1:
	X_BSD_SOURCE             = 1       // features.h:15:1:
	X_FEATURES_H             = 0       // features.h:2:1:
	X_FILE_OFFSET_BITS       = 64      // <builtin>:25:1:
	X_LP64                   = 1       // <predefined>:312:1:
	X_STDC_PREDEF_H          = 1       // <predefined>:174:1:
	X_TIME_H                 = 0       // time.h:2:1:
	X_XOPEN_SOURCE           = 700     // features.h:16:1:
	Linux                    = 1       // <predefined>:255:1:
	Unix                     = 1       // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Time_t = int64 /* alltypes.h:85:16 */

type Timer_t = uintptr /* alltypes.h:209:14 */

type Clockid_t = int32 /* alltypes.h:214:13 */

type Clock_t = int64 /* alltypes.h:219:14 */

type Timespec = struct {
	Ftv_sec  Time_t
	Ftv_nsec int64
} /* alltypes.h:229:1 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Locale_t = uintptr /* alltypes.h:343:32 */

type Tm = struct {
	Ftm_sec      int32
	Ftm_min      int32
	Ftm_hour     int32
	Ftm_mday     int32
	Ftm_mon      int32
	Ftm_year     int32
	Ftm_wday     int32
	Ftm_yday     int32
	Ftm_isdst    int32
	F__ccgo_pad1 [4]byte
	Ftm_gmtoff   int64
	Ftm_zone     uintptr
} /* time.h:38:1 */

type Itimerspec = struct {
	Fit_interval struct {
		Ftv_sec  Time_t
		Ftv_nsec int64
	}
	Fit_value struct {
		Ftv_sec  Time_t
		Ftv_nsec int64
	}
} /* time.h:80:1 */

var _ int8 /* gen.c:2:13: */
