// Code generated by 'ccgo termios/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o termios/termios_linux_amd64.go -pkgname termios -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package termios

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	B0                 = 0000000      // termios.h:80:1:
	B1000000           = 0010010      // termios.h:104:1:
	B110               = 0000003      // termios.h:83:1:
	B115200            = 0010002      // termios.h:98:1:
	B1152000           = 0010011      // termios.h:105:1:
	B1200              = 0000011      // termios.h:89:1:
	B134               = 0000004      // termios.h:84:1:
	B150               = 0000005      // termios.h:85:1:
	B1500000           = 0010012      // termios.h:106:1:
	B1800              = 0000012      // termios.h:90:1:
	B19200             = 0000016      // termios.h:94:1:
	B200               = 0000006      // termios.h:86:1:
	B2000000           = 0010013      // termios.h:107:1:
	B230400            = 0010003      // termios.h:99:1:
	B2400              = 0000013      // termios.h:91:1:
	B2500000           = 0010014      // termios.h:108:1:
	B300               = 0000007      // termios.h:87:1:
	B3000000           = 0010015      // termios.h:109:1:
	B3500000           = 0010016      // termios.h:110:1:
	B38400             = 0000017      // termios.h:95:1:
	B4000000           = 0010017      // termios.h:111:1:
	B460800            = 0010004      // termios.h:100:1:
	B4800              = 0000014      // termios.h:92:1:
	B50                = 0000001      // termios.h:81:1:
	B500000            = 0010005      // termios.h:101:1:
	B57600             = 0010001      // termios.h:97:1:
	B576000            = 0010006      // termios.h:102:1:
	B600               = 0000010      // termios.h:88:1:
	B75                = 0000002      // termios.h:82:1:
	B921600            = 0010007      // termios.h:103:1:
	B9600              = 0000015      // termios.h:93:1:
	BRKINT             = 0000002      // termios.h:31:1:
	BS0                = 0000000      // termios.h:69:1:
	BS1                = 0020000      // termios.h:70:1:
	BSDLY              = 0020000      // termios.h:68:1:
	CBAUD              = 0010017      // termios.h:151:1:
	CBAUDEX            = 0010000      // termios.h:152:1:
	CIBAUD             = 002003600000 // termios.h:153:1:
	CLOCAL             = 0004000      // termios.h:123:1:
	CMSPAR             = 010000000000 // termios.h:154:1:
	CR0                = 0000000      // termios.h:59:1:
	CR1                = 0001000      // termios.h:60:1:
	CR2                = 0002000      // termios.h:61:1:
	CR3                = 0003000      // termios.h:62:1:
	CRDLY              = 0003000      // termios.h:58:1:
	CREAD              = 0000200      // termios.h:119:1:
	CRTSCTS            = 020000000000 // termios.h:155:1:
	CS5                = 0000000      // termios.h:114:1:
	CS6                = 0000020      // termios.h:115:1:
	CS7                = 0000040      // termios.h:116:1:
	CS8                = 0000060      // termios.h:117:1:
	CSIZE              = 0000060      // termios.h:113:1:
	CSTOPB             = 0000100      // termios.h:118:1:
	ECHO               = 0000010      // termios.h:127:1:
	ECHOCTL            = 0001000      // termios.h:158:1:
	ECHOE              = 0000020      // termios.h:128:1:
	ECHOK              = 0000040      // termios.h:129:1:
	ECHOKE             = 0004000      // termios.h:160:1:
	ECHONL             = 0000100      // termios.h:130:1:
	ECHOPRT            = 0002000      // termios.h:159:1:
	EXTA               = 0000016      // termios.h:149:1:
	EXTB               = 0000017      // termios.h:150:1:
	EXTPROC            = 0200000      // termios.h:163:1:
	FEATURES_H         = 0            // features.h:2:1:
	FF0                = 0000000      // termios.h:72:1:
	FF1                = 0100000      // termios.h:73:1:
	FFDLY              = 0100000      // termios.h:71:1:
	FLUSHO             = 0010000      // termios.h:161:1:
	HUPCL              = 0002000      // termios.h:122:1:
	ICANON             = 0000002      // termios.h:126:1:
	ICRNL              = 0000400      // termios.h:38:1:
	IEXTEN             = 0100000      // termios.h:133:1:
	IGNBRK             = 0000001      // termios.h:30:1:
	IGNCR              = 0000200      // termios.h:37:1:
	IGNPAR             = 0000004      // termios.h:32:1:
	IMAXBEL            = 0020000      // termios.h:43:1:
	INLCR              = 0000100      // termios.h:36:1:
	INPCK              = 0000020      // termios.h:34:1:
	ISIG               = 0000001      // termios.h:125:1:
	ISTRIP             = 0000040      // termios.h:35:1:
	IUCLC              = 0001000      // termios.h:39:1:
	IUTF8              = 0040000      // termios.h:44:1:
	IXANY              = 0004000      // termios.h:41:1:
	IXOFF              = 0010000      // termios.h:42:1:
	IXON               = 0002000      // termios.h:40:1:
	NCCS               = 32           // termios.h:18:1:
	NL0                = 0000000      // termios.h:56:1:
	NL1                = 0000400      // termios.h:57:1:
	NLDLY              = 0000400      // termios.h:55:1:
	NOFLSH             = 0000200      // termios.h:131:1:
	OCRNL              = 0000010      // termios.h:49:1:
	OFDEL              = 0000200      // termios.h:53:1:
	OFILL              = 0000100      // termios.h:52:1:
	OLCUC              = 0000002      // termios.h:47:1:
	ONLCR              = 0000004      // termios.h:48:1:
	ONLRET             = 0000040      // termios.h:51:1:
	ONOCR              = 0000020      // termios.h:50:1:
	OPOST              = 0000001      // termios.h:46:1:
	PARENB             = 0000400      // termios.h:120:1:
	PARMRK             = 0000010      // termios.h:33:1:
	PARODD             = 0001000      // termios.h:121:1:
	PENDIN             = 0040000      // termios.h:162:1:
	TAB0               = 0000000      // termios.h:64:1:
	TAB1               = 0004000      // termios.h:65:1:
	TAB2               = 0010000      // termios.h:66:1:
	TAB3               = 0014000      // termios.h:67:1:
	TABDLY             = 0014000      // termios.h:63:1:
	TCIFLUSH           = 0            // termios.h:140:1:
	TCIOFF             = 2            // termios.h:137:1:
	TCIOFLUSH          = 2            // termios.h:142:1:
	TCION              = 3            // termios.h:138:1:
	TCOFLUSH           = 1            // termios.h:141:1:
	TCOOFF             = 0            // termios.h:135:1:
	TCOON              = 1            // termios.h:136:1:
	TCSADRAIN          = 1            // termios.h:145:1:
	TCSAFLUSH          = 2            // termios.h:146:1:
	TCSANOW            = 0            // termios.h:144:1:
	TOSTOP             = 0000400      // termios.h:132:1:
	VDISCARD           = 13           // termios.h:25:1:
	VEOF               = 4            // termios.h:16:1:
	VEOL               = 11           // termios.h:23:1:
	VEOL2              = 16           // termios.h:28:1:
	VERASE             = 2            // termios.h:14:1:
	VINTR              = 0            // termios.h:12:1:
	VKILL              = 3            // termios.h:15:1:
	VLNEXT             = 15           // termios.h:27:1:
	VMIN               = 6            // termios.h:18:1:
	VQUIT              = 1            // termios.h:13:1:
	VREPRINT           = 12           // termios.h:24:1:
	VSTART             = 8            // termios.h:20:1:
	VSTOP              = 9            // termios.h:21:1:
	VSUSP              = 10           // termios.h:22:1:
	VSWTC              = 7            // termios.h:19:1:
	VT0                = 0000000      // termios.h:77:1:
	VT1                = 0040000      // termios.h:78:1:
	VTDLY              = 0040000      // termios.h:76:1:
	VTIME              = 5            // termios.h:17:1:
	VWERASE            = 14           // termios.h:26:1:
	XCASE              = 0000004      // termios.h:157:1:
	XTABS              = 0014000      // termios.h:165:1:
	X_BSD_SOURCE       = 1            // features.h:15:1:
	X_FEATURES_H       = 0            // features.h:2:1:
	X_FILE_OFFSET_BITS = 64           // <builtin>:25:1:
	X_LP64             = 1            // <predefined>:312:1:
	X_STDC_PREDEF_H    = 1            // <predefined>:174:1:
	X_TERMIOS_H        = 0            // termios.h:2:1:
	X_XOPEN_SOURCE     = 700          // features.h:16:1:
	Linux              = 1            // <predefined>:255:1:
	Unix               = 1            // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Pid_t = int32 /* alltypes.h:235:13 */

type Cc_t = uint8      /* termios.h:14:23 */
type Speed_t = uint32  /* termios.h:15:22 */
type Tcflag_t = uint32 /* termios.h:16:22 */

type Termios = struct {
	Fc_iflag     Tcflag_t
	Fc_oflag     Tcflag_t
	Fc_cflag     Tcflag_t
	Fc_lflag     Tcflag_t
	Fc_line      Cc_t
	Fc_cc        [32]Cc_t
	F__ccgo_pad1 [3]byte
	F__c_ispeed  Speed_t
	F__c_ospeed  Speed_t
} /* termios.h:1:1 */

var _ int8 /* gen.c:2:13: */
