// Code generated by 'ccgo poll/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o poll/poll_linux_amd64.go -pkgname poll -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package poll

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	FEATURES_H         = 0      // features.h:2:1:
	POLLERR            = 0x008  // poll.h:15:1:
	POLLHUP            = 0x010  // poll.h:16:1:
	POLLIN             = 0x001  // poll.h:12:1:
	POLLMSG            = 0x400  // poll.h:25:1:
	POLLNVAL           = 0x020  // poll.h:17:1:
	POLLOUT            = 0x004  // poll.h:14:1:
	POLLPRI            = 0x002  // poll.h:13:1:
	POLLRDBAND         = 0x080  // poll.h:19:1:
	POLLRDHUP          = 0x2000 // poll.h:26:1:
	POLLRDNORM         = 0x040  // poll.h:18:1:
	POLLWRBAND         = 0x200  // poll.h:22:1:
	POLLWRNORM         = 0x100  // poll.h:21:1:
	X_BSD_SOURCE       = 1      // features.h:15:1:
	X_FEATURES_H       = 0      // features.h:2:1:
	X_FILE_OFFSET_BITS = 64     // <builtin>:25:1:
	X_LP64             = 1      // <predefined>:312:1:
	X_POLL_H           = 0      // poll.h:2:1:
	X_STDC_PREDEF_H    = 1      // <predefined>:174:1:
	X_XOPEN_SOURCE     = 700    // features.h:16:1:
	Linux              = 1      // <predefined>:255:1:
	Unix               = 1      // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Nfds_t = uint64 /* poll.h:29:23 */

type Pollfd = struct {
	Ffd      int32
	Fevents  int16
	Frevents int16
} /* poll.h:31:1 */

var _ int8 /* gen.c:2:13: */
