// Code generated by 'ccgo sys/stat/gen.c -crt-import-path "" -export-defines "" -export-enums "" -export-externs X -nostdinc -nostdlib -export-fields F -export-structs "" -export-typedefs "" -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o sys/stat/stat_linux_amd64.go -pkgname stat -Imusl-fts/ -Imusl/arch/x86_64 -Imusl/arch/generic -Imusl/obj/src/internal -Imusl/src/include -Imusl/src/internal -Imusl/obj/include -Imusl/include', DO NOT EDIT.

package stat

import (
	"math"
	"reflect"
	"sync/atomic"
	"unsafe"
)

var _ = math.Pi
var _ reflect.Kind
var _ atomic.Value
var _ unsafe.Pointer

const (
	FEATURES_H         = 0          // features.h:2:1:
	S_IEXEC            = 64         // stat.h:98:1:
	S_IFBLK            = 0060000    // stat.h:33:1:
	S_IFCHR            = 0020000    // stat.h:32:1:
	S_IFDIR            = 0040000    // stat.h:31:1:
	S_IFIFO            = 0010000    // stat.h:35:1:
	S_IFLNK            = 0120000    // stat.h:36:1:
	S_IFMT             = 0170000    // stat.h:29:1:
	S_IFREG            = 0100000    // stat.h:34:1:
	S_IFSOCK           = 0140000    // stat.h:37:1:
	S_IREAD            = 256        // stat.h:96:1:
	S_IRGRP            = 0040       // stat.h:60:1:
	S_IROTH            = 0004       // stat.h:64:1:
	S_IRUSR            = 0400       // stat.h:56:1:
	S_IRWXG            = 0070       // stat.h:63:1:
	S_IRWXO            = 0007       // stat.h:67:1:
	S_IRWXU            = 0700       // stat.h:59:1:
	S_ISGID            = 02000      // stat.h:54:1:
	S_ISUID            = 04000      // stat.h:53:1:
	S_ISVTX            = 01000      // stat.h:55:1:
	S_IWGRP            = 0020       // stat.h:61:1:
	S_IWOTH            = 0002       // stat.h:65:1:
	S_IWRITE           = 128        // stat.h:97:1:
	S_IWUSR            = 0200       // stat.h:57:1:
	S_IXGRP            = 0010       // stat.h:62:1:
	S_IXOTH            = 0001       // stat.h:66:1:
	S_IXUSR            = 0100       // stat.h:58:1:
	UTIME_NOW          = 0x3fffffff // stat.h:70:1:
	UTIME_OMIT         = 0x3ffffffe // stat.h:71:1:
	X_BSD_SOURCE       = 1          // features.h:15:1:
	X_FEATURES_H       = 0          // features.h:2:1:
	X_FILE_OFFSET_BITS = 64         // <builtin>:25:1:
	X_LP64             = 1          // <predefined>:312:1:
	X_STDC_PREDEF_H    = 1          // <predefined>:174:1:
	X_SYS_STAT_H       = 0          // stat.h:2:1:
	X_XOPEN_SOURCE     = 700        // features.h:16:1:
	Linux              = 1          // <predefined>:255:1:
	Unix               = 1          // <predefined>:191:1:
)

type Ptrdiff_t = int64 /* <builtin>:3:26 */

type Size_t = uint64 /* <builtin>:9:23 */

type Wchar_t = int32 /* <builtin>:15:24 */

type X__int128_t = struct {
	Flo int64
	Fhi int64
} /* <builtin>:21:43 */ // must match modernc.org/mathutil.Int128
type X__uint128_t = struct {
	Flo uint64
	Fhi uint64
} /* <builtin>:22:44 */ // must match modernc.org/mathutil.Int128

type X__builtin_va_list = uintptr /* <builtin>:46:14 */
type X__float128 = float64        /* <builtin>:47:21 */

type Time_t = int64 /* alltypes.h:85:16 */

type Mode_t = uint32 /* alltypes.h:152:18 */

type Nlink_t = uint64 /* alltypes.h:157:23 */

type Off_t = int64 /* alltypes.h:162:16 */

type Ino_t = uint64 /* alltypes.h:167:25 */

type Dev_t = uint64 /* alltypes.h:172:25 */

type Blksize_t = int64 /* alltypes.h:177:14 */

type Blkcnt_t = int64 /* alltypes.h:182:16 */

type Timespec = struct {
	Ftv_sec  Time_t
	Ftv_nsec int64
} /* alltypes.h:229:1 */

type Uid_t = uint32 /* alltypes.h:245:18 */

type Gid_t = uint32 /* alltypes.h:250:18 */

// copied from kernel definition, but with padding replaced
// by the corresponding correctly-sized userspace types.

type Stat = struct {
	Fst_dev     Dev_t
	Fst_ino     Ino_t
	Fst_nlink   Nlink_t
	Fst_mode    Mode_t
	Fst_uid     Uid_t
	Fst_gid     Gid_t
	F__pad0     uint32
	Fst_rdev    Dev_t
	Fst_size    Off_t
	Fst_blksize Blksize_t
	Fst_blocks  Blkcnt_t
	Fst_atim    struct {
		Ftv_sec  Time_t
		Ftv_nsec int64
	}
	Fst_mtim struct {
		Ftv_sec  Time_t
		Ftv_nsec int64
	}
	Fst_ctim struct {
		Ftv_sec  Time_t
		Ftv_nsec int64
	}
	F__unused [3]int64
} /* stat.h:4:1 */

var _ int8 /* gen.c:2:13: */
